language: python

python:
  - 3.6

services: mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=ERP.settings_travis
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ERP_travisci character set UTF8;'

script:
  - flake8
  - coverage run manage.py test -v 2 --debug-mode

notifications:
    email: false

after_success:
    coveralls
