language: python

python:
  - 3.6

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=ERP.settings_travis
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE ERP_travis;" -U postgres

script:
  - flake8
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test

notifications:
    email: false
