# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:21
from __future__ import unicode_literals

import Core.utils.hash
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to=Core.utils.hash.DynamicHashPath('BiddingDocument'), verbose_name='路径')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('status', models.IntegerField(choices=[(-1, '未审核'), (0, '通过'), (1, '不通过')], default=-1, verbose_name='状态')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_doc_dst', to='Core.Department', verbose_name='接收部门')),
            ],
            options={
                'verbose_name': '产品招标文件',
                'verbose_name_plural': '产品招标文件',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('terminated', models.BooleanField(default=False, verbose_name='终止状态')),
                ('status', models.IntegerField(choices=[(-1, '未审核'), (0, '通过'), (1, '不通过')], default=-1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品"',
            },
        ),
        migrations.AddField(
            model_name='biddingdocument',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Distribution.Product', verbose_name='对应产品'),
        ),
        migrations.AddField(
            model_name='biddingdocument',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_doc_src', to='Core.Department', verbose_name='来源部门'),
        ),
    ]
