# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('path', models.FileField(upload_to='%Y/%m/%d', verbose_name='路径')),
                ('size', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='大小')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('approved', models.IntegerField(choices=[(-1, '未审核'), (0, '通过'), (1, '不通过')], default=-1, verbose_name='审核结果')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidfile_dst', to='Core.Department', verbose_name='接收部门')),
            ],
            options={
                'verbose_name': '招标文件',
                'verbose_name_plural': '招标文件',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('approved', models.IntegerField(choices=[(-1, '未审核'), (0, '通过'), (1, '不通过')], default=-1, verbose_name='产品审核结果')),
                ('terminated', models.BooleanField(default=False, verbose_name='终止状态')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品"',
            },
        ),
        migrations.AddField(
            model_name='bidfile',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribution.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidfile_src', to='Core.Department', verbose_name='来源部门'),
        ),
    ]
