# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, verbose_name='简写')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='SubWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('finished', models.BooleanField(default=False, verbose_name='已结束')),
            ],
            options={
                'verbose_name': '子工作令',
                'verbose_name_plural': '子工作令',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='电话')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='移动电话')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('sell_type', models.IntegerField(choices=[(0, '内销'), (1, '外销')], verbose_name='销售类型')),
                ('client', models.CharField(max_length=100, verbose_name='客户名称')),
                ('project', models.CharField(max_length=100, verbose_name='项目名称')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('finished', models.BooleanField(default=False, verbose_name='已结束')),
            ],
            options={
                'verbose_name': '工作令',
                'verbose_name_plural': '工作令',
            },
        ),
    ]
