# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名')),
                ('short_name', models.CharField(max_length=50, verbose_name='简写')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='材料名称')),
                ('material_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='材料编号')),
                ('category', models.IntegerField(blank=True, choices=[(1, '焊条'), (2, '焊丝'), (3, '焊带'), (4, '焊剂'), (5, '板材'), (6, '型材'), (7, '外购件'), (8, '辅助工具'), (0, '其他')], null=True, verbose_name='材料类别')),
            ],
            options={
                'verbose_name': '材料',
                'verbose_name_plural': '材料',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=20, verbose_name='票号')),
                ('sub_index', models.CharField(blank=True, max_length=20, null=True, verbose_name='部件号')),
                ('schematic_index', models.CharField(blank=True, max_length=50, null=True, verbose_name='图号')),
                ('parent_schematic_index', models.CharField(blank=True, max_length=50, null=True, verbose_name='部件图号')),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部件名称')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名称')),
                ('count', models.CharField(blank=True, max_length=20, null=True, verbose_name='数量')),
                ('net_weight', models.FloatField(blank=True, null=True, verbose_name='净重')),
                ('total_weight', models.FloatField(blank=True, null=True, verbose_name='毛重')),
                ('quota', models.FloatField(blank=True, null=True, verbose_name='定额')),
                ('quota_coefficient', models.FloatField(blank=True, null=True, verbose_name='定额系数')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('specification', models.CharField(blank=True, max_length=20, null=True, verbose_name='规格')),
                ('standard', models.CharField(blank=True, max_length=20, null=True, verbose_name='标准')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('press', models.CharField(blank=True, max_length=20, null=True, verbose_name='受压')),
                ('recheck', models.CharField(blank=True, max_length=20, null=True, verbose_name='复验')),
                ('detection_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='探伤级别')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Material', verbose_name='材质')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
            },
        ),
        migrations.CreateModel(
            name='SubWorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('name', models.CharField(max_length=100, verbose_name='工作令名')),
                ('finished', models.BooleanField(default=False, verbose_name='是否结束')),
            ],
            options={
                'verbose_name': '子工作令',
                'verbose_name_plural': '子工作令',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='移动电话')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True, verbose_name='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('sell_type', models.IntegerField(choices=[(0, '内销'), (1, '外销')], verbose_name='销售类型')),
                ('client', models.CharField(max_length=100, verbose_name='客户名称')),
                ('project', models.CharField(max_length=100, verbose_name='项目名称')),
                ('product', models.CharField(max_length=100, verbose_name='产品名称')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('finished', models.BooleanField(default=False, verbose_name='是否结束')),
            ],
            options={
                'verbose_name': '工作令',
                'verbose_name_plural': '工作令',
            },
        ),
        migrations.AddField(
            model_name='subworkorder',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='所属工作令'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='所属工作令'),
        ),
    ]
