# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0001_initial'),
        ('Distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Distribution.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='subworkorder',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='所属工作令'),
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='组'),
        ),
        migrations.AddField(
            model_name='department',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.Department', verbose_name='上级部门'),
        ),
    ]
