# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20171206_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='组'),
        ),
    ]
