# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Procurement', '0001_initial'),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_coef', models.CharField(blank=True, max_length=100, null=True, verbose_name='定额系数')),
                ('quota', models.FloatField(blank=True, null=True, verbose_name='定额')),
                ('stardard_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='标准代码')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属物料')),
            ],
            options={
                'verbose_name': '辅材',
                'verbose_name_plural': '辅材',
            },
        ),
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'H1'), (1, 'J'), (4, 'ZM'), (3, 'R'), (5, 'GY'), (6, 'DY'), (7, 'XZ')], verbose_name='简称')),
                ('full_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='全称')),
            ],
            options={
                'verbose_name': '流转',
                'verbose_name_plural': '流转名称',
            },
        ),
        migrations.CreateModel(
            name='CirculationRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属物料')),
            ],
            options={
                'verbose_name': '流转路线',
                'verbose_name_plural': '流转路线',
            },
        ),
        migrations.CreateModel(
            name='ConnectOrientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名称')),
                ('path', models.FileField(upload_to='%Y/%m/%d', verbose_name='文件路径')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('size', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文件类型')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='所属工作令')),
            ],
            options={
                'verbose_name': '管口方位图',
                'verbose_name_plural': '管口方位图',
            },
        ),
        migrations.CreateModel(
            name='CooperantItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属物料')),
            ],
            options={
                'verbose_name': '工序性外协件',
                'verbose_name_plural': '工序性外协件',
            },
        ),
        migrations.CreateModel(
            name='FirstFeedingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属物料')),
            ],
            options={
                'verbose_name': '先投件',
                'verbose_name_plural': '先投件',
            },
        ),
        migrations.CreateModel(
            name='HeatTreatmentPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_heat_treat_thick', models.CharField(blank=True, max_length=20, null=True, verbose_name='最大热处理厚度')),
                ('heat_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='热处理检验')),
                ('test_result', models.CharField(blank=True, max_length=100, null=True, verbose_name='检验结果')),
            ],
            options={
                'verbose_name': '热处理件',
                'verbose_name_plural': '热处理件',
            },
        ),
        migrations.CreateModel(
            name='HeatTreatmentTechCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件编号')),
                ('write_date', models.DateField(blank=True, null=True, verbose_name='编制日期')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='审核日期')),
                ('furnace_temp', models.CharField(blank=True, max_length=20, null=True, verbose_name='进炉温度')),
                ('tapping_temp', models.CharField(blank=True, max_length=20, null=True, verbose_name='出炉温度')),
                ('maximum_temp', models.CharField(blank=True, max_length=20, null=True, verbose_name='最高温度')),
                ('heating_rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='升温速率')),
                ('cooling_rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='降温速率')),
                ('holding_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='保温时间')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_treat_tech_card_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_treat_tech_card_writer', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
            ],
            options={
                'verbose_name': '热处理工艺卡',
                'verbose_name_plural': '热处理工艺卡',
            },
        ),
        migrations.CreateModel(
            name='HeatTreatmentTempMeasuringPointLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件编号')),
                ('write_date', models.DateField(blank=True, null=True, verbose_name='编制日期')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='审核日期')),
                ('path', models.FileField(upload_to='%Y/%m/%d', verbose_name='文件路径')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HTTMPL_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('tech_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Process.HeatTreatmentTechCard', verbose_name='所属工艺卡')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HTTMPL_writer', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
            ],
            options={
                'verbose_name': '热处理测温点布置',
                'verbose_name_plural': '热处理测温点布置',
            },
        ),
        migrations.CreateModel(
            name='NondestructiveInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'RT'), (1, 'UT'), (2, 'MT'), (3, 'PT'), (4, 'VT')], max_length=20, verbose_name='探伤种类名')),
            ],
            options={
                'verbose_name': '无损探伤',
                'verbose_name_plural': '无损探伤',
            },
        ),
        migrations.CreateModel(
            name='OutPurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属物料')),
            ],
            options={
                'verbose_name': '外购件',
                'verbose_name_plural': '外购件',
            },
        ),
        migrations.CreateModel(
            name='PrincipalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格')),
                ('count', models.CharField(blank=True, max_length=100, null=True, verbose_name='数量')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='单重')),
                ('stardard', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行标准')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='供货状态')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.Material', verbose_name='材质')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='所属工作令')),
            ],
            options={
                'verbose_name': '主材',
                'verbose_name_plural': '主材',
            },
        ),
        migrations.CreateModel(
            name='ProcedureQualificationIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'RH24-13-09'), (1, 'RH24-13-36')], verbose_name='焊接工艺评定编号')),
            ],
            options={
                'verbose_name': '焊接工艺评定编号',
                'verbose_name_plural': '焊接工艺评定编号',
            },
        ),
        migrations.CreateModel(
            name='ProcessLibrarySignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_date', models.DateField(blank=True, null=True, verbose_name='编制日期')),
                ('quota_date', models.DateField(blank=True, null=True, verbose_name='定额日期')),
                ('proofread_date', models.DateField(blank=True, null=True, verbose_name='校对日期')),
                ('statistic_date', models.DateField(blank=True, null=True, verbose_name='统计日期')),
                ('proofreader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_proofreader', to=settings.AUTH_USER_MODEL, verbose_name='校对人')),
                ('quota_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_quota_clerk', to=settings.AUTH_USER_MODEL, verbose_name='定额员')),
                ('statistician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_statistician', to=settings.AUTH_USER_MODEL, verbose_name='统计员')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='所属工作令')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_signature_writer', to=settings.AUTH_USER_MODEL, verbose_name='工艺员')),
            ],
            options={
                'verbose_name': '工艺库签章',
                'verbose_name_plural': '工艺库签章',
            },
        ),
        migrations.CreateModel(
            name='ProcessReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(blank=True, max_length=200, null=True, verbose_name='存在问题')),
                ('advice', models.CharField(blank=True, max_length=200, null=True, verbose_name='改进建议')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='零件')),
            ],
            options={
                'verbose_name': '工艺性审查表',
                'verbose_name_plural': '工艺性审查表',
            },
        ),
        migrations.CreateModel(
            name='ProcessRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属物料')),
            ],
            options={
                'verbose_name': '工序路线',
                'verbose_name_plural': '工序路线',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'W'), (1, 'W1'), (2, 'W2'), (3, 'W3'), (4, 'W4'), (5, 'W5'), (6, 'W6'), (7, 'W25'), (8, 'P01'), (9, 'P02'), (10, 'R'), (11, 'R1'), (12, 'R2'), (13, 'Z'), (14, 'H'), (15, 'M'), (16, 'L'), (17, 'Y'), (18, 'G'), (19, 'G1'), (20, 'G2'), (21, 'G3'), (22, 'G4'), (23, 'G5'), (24, 'X'), (25, 'J'), (28, 'D'), (27, 'D2'), (26, 'K')], verbose_name='工序')),
                ('man_hours', models.CharField(blank=True, max_length=20, null=True, verbose_name='工时')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessRoute', verbose_name='工序路线')),
            ],
            options={
                'verbose_name': '工序步骤',
            },
        ),
        migrations.CreateModel(
            name='ProgramingNestingChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名称')),
                ('path', models.FileField(upload_to='%Y/%m/%d', verbose_name='文件路径')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('size', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文件类型')),
                ('execution_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.MaterielExecutionDetail', verbose_name='所属执行')),
            ],
            options={
                'verbose_name': '编程套料图',
                'verbose_name_plural': '编程套料图',
            },
        ),
        migrations.CreateModel(
            name='TechPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='详细内容')),
                ('estimated_finish_date', models.DateField(verbose_name='计划完成时间')),
                ('month', models.IntegerField(verbose_name='所属月份')),
                ('year', models.IntegerField(verbose_name='所属年份')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Department', verbose_name='下发部门')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.WorkOrder', verbose_name='所属工作令')),
            ],
            options={
                'verbose_name': '技术准备计划',
                'verbose_name_plural': '技术准备计划',
            },
        ),
        migrations.CreateModel(
            name='TransferCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件编号')),
                ('category', models.IntegerField(choices=[(0, '筒体流转卡'), (1, '封头流转卡'), (2, '焊接试板流转卡'), (3, '母材试板流转卡'), (4, '受压元件流转卡'), (5, '特别元件流转卡')], verbose_name='流转卡类型')),
                ('container_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='容器类别')),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属部件名称')),
                ('weld_test_plate_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='焊接试板图号')),
                ('parent_test_plate_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材试板图号')),
                ('material_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='材质标记')),
                ('path', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='文件路径')),
                ('tech_requirement', models.CharField(blank=True, max_length=1000, null=True, verbose_name='技术要求')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属零件')),
            ],
            options={
                'verbose_name': '流转卡',
                'verbose_name_plural': '流转卡',
            },
        ),
        migrations.CreateModel(
            name='TransferCardProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=100, null=True, verbose_name='序号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='工序名')),
                ('detail', models.CharField(blank=True, max_length=1000, null=True, verbose_name='工艺过程及技术要求')),
                ('transfer_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.TransferCard', verbose_name='流转卡')),
            ],
            options={
                'verbose_name': '流转卡工序',
                'verbose_name_plural': '流转卡工序',
            },
        ),
        migrations.CreateModel(
            name='TransferCardSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_date', models.DateField(blank=True, null=True, verbose_name='编制日期')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='审核日期')),
                ('proofread_date', models.DateField(blank=True, null=True, verbose_name='校对日期')),
                ('approve_date', models.DateField(blank=True, null=True, verbose_name='批准日期')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_card_signature_approver', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('proofreader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_card_signature_proofreader', to=settings.AUTH_USER_MODEL, verbose_name='校对人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_card_signature_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('transfer_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Process.TransferCard', verbose_name='所属流转卡')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_card_signature_writer', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
            ],
            options={
                'verbose_name': '流转卡签章',
                'verbose_name_plural': '流转卡签章',
            },
        ),
        migrations.CreateModel(
            name='WeldCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='焊工持证项目')),
            ],
            options={
                'verbose_name': '焊工持证项目',
                'verbose_name_plural': '焊工持证项目',
            },
        ),
        migrations.CreateModel(
            name='WeldingProcessSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='编制日期')),
                ('audit_date', models.DateField(blank=True, null=True, verbose_name='审核日期')),
                ('approve_date', models.DateField(blank=True, null=True, verbose_name='批准日期')),
                ('path', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='示意图')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_proc_sped_approver', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_proc_spec_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('lister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_proc_spec_lister', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='所属工作令')),
            ],
            options={
                'verbose_name': '焊接工艺规程',
                'verbose_name_plural': '焊接工艺规程',
            },
        ),
        migrations.CreateModel(
            name='WeldingStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(blank=True, max_length=100, null=True, verbose_name='层/道')),
                ('polarity', models.CharField(blank=True, max_length=100, null=True, verbose_name='极性')),
                ('electricity', models.CharField(blank=True, max_length=100, null=True, verbose_name='电流')),
                ('voltage', models.CharField(blank=True, max_length=100, null=True, verbose_name='电流电压')),
                ('welding_speed', models.CharField(blank=True, max_length=100, null=True, verbose_name='焊接速度')),
                ('heat_input', models.CharField(blank=True, max_length=100, null=True, verbose_name='线能量')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '焊接层道卡',
                'verbose_name_plural': '焊接层道卡',
            },
        ),
        migrations.CreateModel(
            name='WeldingWorkInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='编制日期')),
                ('audit_date', models.DateField(blank=True, null=True, verbose_name='审核日期')),
                ('proofread_date', models.DateField(blank=True, null=True, verbose_name='校对日期')),
                ('approve_date', models.DateField(blank=True, null=True, verbose_name='批准日期')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件编号')),
                ('path', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='简图')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_work_inst_approver', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_work_inst_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '焊接作业指导书',
                'verbose_name_plural': '焊接作业指导书',
            },
        ),
        migrations.CreateModel(
            name='WeldingWorkInstructionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=100, null=True, verbose_name='序号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='工序名')),
                ('detail', models.CharField(blank=True, max_length=1000, null=True, verbose_name='工艺过程及技术要求')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldingWorkInstruction', verbose_name='焊接作业指导书')),
            ],
            options={
                'verbose_name': '焊接作业指导书工序',
                'verbose_name_plural': '焊接作业指导书工序',
            },
        ),
        migrations.CreateModel(
            name='WeldingWorkInstructionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(blank=True, max_length=100, null=True, verbose_name='序号')),
                ('test_method', models.IntegerField(blank=True, choices=[(0, '厂内'), (1, '检验机构'), (2, '第三方或用户')], null=True, verbose_name='检验方')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldingWorkInstruction', verbose_name='焊接作业指导书')),
            ],
            options={
                'verbose_name': '焊接作业检验',
                'verbose_name_plural': '焊接作业检验',
            },
        ),
        migrations.CreateModel(
            name='WeldJointTechDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joint_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='接头编号')),
                ('bm_texture_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材材质_1')),
                ('bm_spec_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材规格_1')),
                ('bm_texture_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材材质_2')),
                ('bm_spec_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材规格_2')),
                ('proc_qual_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='焊接工艺评定编号')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldingProcessSpecification', verbose_name='焊接工艺规程')),
                ('weld_cert_1', models.ManyToManyField(related_name='joint_detail_cert_1', to='Process.WeldCertification', verbose_name='焊工持证项目_1')),
                ('weld_cert_2', models.ManyToManyField(related_name='joint_detail_cert_2', to='Process.WeldCertification', verbose_name='焊工持证项目_2')),
            ],
            options={
                'verbose_name': '焊接接头工艺分析',
                'verbose_name_plural': '焊接接头工艺分析',
            },
        ),
        migrations.CreateModel(
            name='WeldMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, '焊条电弧焊'), (1, '埋弧焊'), (2, '气体保护焊'), (3, '氩弧焊')], max_length=100, verbose_name='方法名')),
            ],
            options={
                'verbose_name': '焊接方法',
                'verbose_name_plural': '焊接方法',
            },
        ),
        migrations.CreateModel(
            name='WeldPositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, '平焊'), (1, '横焊'), (2, '仰焊'), (3, '立向上焊'), (4, '全位置焊')], verbose_name='焊接位置名')),
            ],
            options={
                'verbose_name': '焊接位置',
                'verbose_name_plural': '焊接位置',
            },
        ),
        migrations.CreateModel(
            name='WeldQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格')),
                ('quota', models.FloatField(blank=True, null=True, verbose_name='定额')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('stardard', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行标准')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Material', verbose_name='焊材')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.WorkOrder', verbose_name='所属工作令')),
            ],
            options={
                'verbose_name': '焊材定额',
                'verbose_name_plural': '焊材定额',
            },
        ),
        migrations.CreateModel(
            name='WeldSeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='焊缝编号')),
                ('base_metal_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材材质_1')),
                ('base_metal_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材材质_2')),
                ('base_metal_thick_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材厚度_1')),
                ('base_metal_thick_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='母材厚度2')),
                ('length', models.CharField(max_length=100, verbose_name='长度')),
                ('thick_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='焊材厚度_1')),
                ('size_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格_1')),
                ('weight_1', models.FloatField(blank=True, default=0, verbose_name='重量_1')),
                ('flux_weight_1', models.FloatField(blank=True, default=0, verbose_name='焊剂重量_1')),
                ('thick_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='焊材厚度_2')),
                ('size_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格_2')),
                ('weight_2', models.FloatField(blank=True, default=0, verbose_name='重量_2')),
                ('flux_weight_2', models.FloatField(blank=True, default=0, verbose_name='焊剂重量_2')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('groove_inspction', models.ManyToManyField(blank=True, related_name='weld_seam_groove_inspction', to='Process.NondestructiveInspection', verbose_name='坡口探伤')),
                ('heat_treatment_inspection', models.ManyToManyField(blank=True, related_name='weld_seam_heat_treatment_inspection', to='Process.NondestructiveInspection', verbose_name='热处理后探伤')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='所属物料')),
                ('pressure_test_inspection', models.ManyToManyField(blank=True, related_name='weld_seam_pressure_test_inspection', to='Process.NondestructiveInspection', verbose_name='试压后探伤')),
            ],
            options={
                'verbose_name': '焊缝',
                'verbose_name_plural': '焊缝',
            },
        ),
        migrations.CreateModel(
            name='WeldSeamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名')),
            ],
            options={
                'verbose_name': '焊缝类型',
                'verbose_name_plural': '焊缝类型',
            },
        ),
        migrations.AddField(
            model_name='weldseam',
            name='seam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldSeamType', verbose_name='焊缝类型'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_flux_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_flux_1', to='Core.Material', verbose_name='焊剂_1'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_flux_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weld_seam_flux_2', to='Core.Material', verbose_name='焊剂_2'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_joint_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Process.WeldJointTechDetail', verbose_name='焊接接头'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_material_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_material_1', to='Core.Material', verbose_name='焊丝/焊条_1'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_material_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_material_2', to='Core.Material', verbose_name='焊丝/焊条_2'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_method_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_method_1', to='Process.WeldMethod', verbose_name='焊接方法_1'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_method_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_method_2', to='Process.WeldMethod', verbose_name='焊接方法_2'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='weld_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldPositionType', verbose_name='焊接位置'),
        ),
        migrations.AddField(
            model_name='weldseam',
            name='welded_status_inspection',
            field=models.ManyToManyField(blank=True, related_name='weld_seam_welded_status_inspection', to='Process.NondestructiveInspection', verbose_name='焊态探伤'),
        ),
        migrations.AddField(
            model_name='weldjointtechdetail',
            name='weld_method_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_detail_method_1', to='Process.WeldMethod', verbose_name='焊接方法_1'),
        ),
        migrations.AddField(
            model_name='weldjointtechdetail',
            name='weld_method_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_detail_method_2', to='Process.WeldMethod', verbose_name='焊接方法_2'),
        ),
        migrations.AddField(
            model_name='weldjointtechdetail',
            name='weld_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldPositionType', verbose_name='焊接位置'),
        ),
        migrations.AddField(
            model_name='weldingworkinstruction',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldJointTechDetail', verbose_name='所属接头分析'),
        ),
        migrations.AddField(
            model_name='weldingworkinstruction',
            name='lister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_work_inst_lister', to=settings.AUTH_USER_MODEL, verbose_name='编制人'),
        ),
        migrations.AddField(
            model_name='weldingworkinstruction',
            name='proofreader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_work_inst_proofreader', to=settings.AUTH_USER_MODEL, verbose_name='校对人'),
        ),
        migrations.AddField(
            model_name='weldingstep',
            name='instruction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldingWorkInstruction', verbose_name='焊接作业指导书'),
        ),
        migrations.AddField(
            model_name='weldingstep',
            name='weld_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Process.WeldMethod', verbose_name='所属焊接方法'),
        ),
        migrations.AddField(
            model_name='weldcertification',
            name='weld_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.WeldMethod', verbose_name='所属焊接方法'),
        ),
        migrations.AddField(
            model_name='heattreatmentpart',
            name='card_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Process.HeatTreatmentTechCard', verbose_name='所属工艺卡'),
        ),
        migrations.AddField(
            model_name='heattreatmentpart',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='零件'),
        ),
        migrations.AddField(
            model_name='heattreatmentpart',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='circulation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.CirculationRoute', verbose_name='流转路线'),
        ),
    ]
