# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Process', '0001_initial'),
        ('Core', '0002_auto_20171130_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmingblankingchart',
            name='execution_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.MaterialExecutionDetail', verbose_name='材料执行表详细情况'),
        ),
        migrations.AddField(
            model_name='processroute',
            name='materiel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='processreview',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='零件'),
        ),
        migrations.AddField(
            model_name='processmaterial',
            name='lib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessLibrary', verbose_name='工艺库'),
        ),
        migrations.AddField(
            model_name='processmaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Process.Material', verbose_name='材质'),
        ),
        migrations.AddField(
            model_name='processlibrary',
            name='proofreader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_proofreader', to=settings.AUTH_USER_MODEL, verbose_name='校对人'),
        ),
        migrations.AddField(
            model_name='processlibrary',
            name='quota_clerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_quota_clerk', to=settings.AUTH_USER_MODEL, verbose_name='定额员'),
        ),
        migrations.AddField(
            model_name='processlibrary',
            name='statistician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_statistician', to=settings.AUTH_USER_MODEL, verbose_name='统计员'),
        ),
        migrations.AddField(
            model_name='processlibrary',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='工作令'),
        ),
        migrations.AddField(
            model_name='processlibrary',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lib_writer', to=settings.AUTH_USER_MODEL, verbose_name='工艺员'),
        ),
        migrations.AddField(
            model_name='principalquotaitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Process.Material', verbose_name='材质'),
        ),
        migrations.AddField(
            model_name='principalquotaitem',
            name='quota_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.QuotaList', verbose_name='定额明细表'),
        ),
        migrations.AddField(
            model_name='firstfeedingitem',
            name='materiel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firstfeedingitem', to='Process.ProcessMaterial', verbose_name='工艺物料'),
        ),
        migrations.AddField(
            model_name='firstfeedingitem',
            name='quota_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.QuotaList', verbose_name='定额明细表'),
        ),
        migrations.AddField(
            model_name='cooperantitem',
            name='materiel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooperantitem', to='Process.ProcessMaterial', verbose_name='工艺物料'),
        ),
        migrations.AddField(
            model_name='cooperantitem',
            name='quota_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.QuotaList', verbose_name='定额明细表'),
        ),
        migrations.AddField(
            model_name='circulationroute',
            name='materiel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='boughtinitem',
            name='materiel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boughtinitem', to='Process.ProcessMaterial', verbose_name='工艺物料'),
        ),
        migrations.AddField(
            model_name='boughtinitem',
            name='quota_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.QuotaList', verbose_name='定额明细表'),
        ),
        migrations.AddField(
            model_name='auxiliaryquotaitem',
            name='materiel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliaryquotaitem', to='Process.ProcessMaterial', verbose_name='工艺物料'),
        ),
        migrations.AddField(
            model_name='auxiliaryquotaitem',
            name='quota_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.QuotaList', verbose_name='定额明细表'),
        ),
    ]
