# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0003_auto_20171212_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '焊条'), (2, '焊丝'), (3, '焊带'), (4, '焊剂'), (5, '板材'), (6, '型材'), (7, '外购件'), (8, '辅助工具'), (0, '其他')], null=True, verbose_name='材质类别'),
        ),
    ]
