# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0005_auto_20171212_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmaterial',
            name='piece_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='净重'),
        ),
    ]
