# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0006_auto_20171212_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(blank=True, choices=[(0, 'W'), (1, 'W1'), (2, 'W2'), (3, 'W3'), (4, 'W4'), (5, 'W5'), (6, 'W6'), (7, 'W25'), (8, 'P01'), (9, 'P02'), (10, 'R'), (11, 'R1'), (12, 'R2'), (13, 'Z'), (14, 'H'), (15, 'M'), (16, 'L'), (17, 'Y'), (18, 'G'), (19, 'G1'), (20, 'G2'), (21, 'G3'), (22, 'G4'), (23, 'G5'), (24, 'X'), (25, 'J'), (28, 'D'), (27, 'D2'), (26, 'K')], null=True, verbose_name='工序')),
                ('man_hours', models.FloatField(blank=True, null=True, verbose_name='工时')),
            ],
            options={
                'verbose_name': '工序步骤',
                'verbose_name_plural': '工序步骤',
            },
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H1',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H10',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H11',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H12',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H2',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H3',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H4',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H5',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H6',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H7',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H8',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='H9',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S1',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S10',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S11',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S12',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S2',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S3',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S4',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S5',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S6',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S7',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S8',
        ),
        migrations.RemoveField(
            model_name='processroute',
            name='S9',
        ),
        migrations.AddField(
            model_name='processstep',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Process.ProcessRoute', verbose_name='工序路线'),
        ),
    ]
