# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0007_auto_20171214_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlibrary',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_library', to='Core.WorkOrder', verbose_name='工作令'),
        ),
        migrations.AlterField(
            model_name='processmaterial',
            name='lib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_materials', to='Process.ProcessLibrary', verbose_name='工艺库'),
        ),
    ]
