# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0008_auto_20171218_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auxiliaryquotaitem',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='boughtinitem',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='circulationroute',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='cooperantitem',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='firstfeedingitem',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='processreview',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='processroute',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='transfercard',
            old_name='materiel',
            new_name='process_material',
        ),
        migrations.RenameField(
            model_name='weldingseam',
            old_name='materiel',
            new_name='process_material',
        ),
    ]
