# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0010_auto_20171221_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processlibrary',
            old_name='proofread_date',
            new_name='proofread_dt',
        ),
        migrations.RenameField(
            model_name='processlibrary',
            old_name='quota_date',
            new_name='quota_dt',
        ),
        migrations.RenameField(
            model_name='processlibrary',
            old_name='statistic_date',
            new_name='statistic_dt',
        ),
        migrations.RenameField(
            model_name='processlibrary',
            old_name='write_date',
            new_name='write_dt',
        ),
        migrations.RenameField(
            model_name='quotalist',
            old_name='review_date',
            new_name='review_dt',
        ),
        migrations.RenameField(
            model_name='quotalist',
            old_name='write_date',
            new_name='write_dt',
        ),
        migrations.RenameField(
            model_name='transfercard',
            old_name='approve_date',
            new_name='approve_dt',
        ),
        migrations.RenameField(
            model_name='transfercard',
            old_name='proofread_date',
            new_name='proofread_dt',
        ),
        migrations.RenameField(
            model_name='transfercard',
            old_name='review_date',
            new_name='review_dt',
        ),
        migrations.RenameField(
            model_name='transfercard',
            old_name='write_date',
            new_name='write_dt',
        ),
        migrations.RenameField(
            model_name='weldingprocessspecification',
            old_name='approve_date',
            new_name='approve_dt',
        ),
        migrations.RenameField(
            model_name='weldingprocessspecification',
            old_name='audit_date',
            new_name='audit_dt',
        ),
        migrations.RenameField(
            model_name='weldingprocessspecification',
            old_name='list_date',
            new_name='list_dt',
        ),
        migrations.RenameField(
            model_name='weldingworkinstruction',
            old_name='approve_date',
            new_name='approve_dt',
        ),
        migrations.RenameField(
            model_name='weldingworkinstruction',
            old_name='audit_date',
            new_name='audit_dt',
        ),
        migrations.RenameField(
            model_name='weldingworkinstruction',
            old_name='list_date',
            new_name='list_dt',
        ),
        migrations.RenameField(
            model_name='weldingworkinstruction',
            old_name='proofread_date',
            new_name='proofread_dt',
        ),
    ]
