# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0012_transfercard_file_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercard',
            name='parent_name',
        ),
    ]
