# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0013_remove_transfercard_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercard',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='所属部件名称'),
        ),
    ]
