# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0014_transfercard_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationroute',
            name='process_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='circulation_route', to='Process.ProcessMaterial', verbose_name='物料'),
        ),
    ]
