# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-26 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0016_auto_20171226_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principalquotaitem',
            name='lib',
        ),
        migrations.RemoveField(
            model_name='weldingquotaitem',
            name='lib',
        ),
    ]
