# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0017_auto_20171226_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliaryquotaitem',
            name='quota',
            field=models.FloatField(blank=True, null=True, verbose_name='定额'),
        ),
        migrations.AlterField(
            model_name='auxiliaryquotaitem',
            name='quota_coef',
            field=models.FloatField(blank=True, null=True, verbose_name='定额系数'),
        ),
    ]
