# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0018_auto_20171228_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxMaterial',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('Process.material',),
        ),
        migrations.CreateModel(
            name='TotalWeldingMaterial',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('Process.material',),
        ),
        migrations.CreateModel(
            name='WeldingMaterial',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('Process.material',),
        ),
        migrations.AlterField(
            model_name='transfercard',
            name='process_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_card', to='Process.ProcessMaterial', verbose_name='工艺物料'),
        ),
        migrations.AlterField(
            model_name='weldingquotaitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Process.TotalWeldingMaterial', verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='weldingseam',
            name='wf_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_flux_1', to='Process.FluxMaterial', verbose_name='焊丝/焊条_1_焊剂'),
        ),
        migrations.AlterField(
            model_name='weldingseam',
            name='wf_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_flux_2', to='Process.FluxMaterial', verbose_name='焊丝/焊条_2_焊剂'),
        ),
        migrations.AlterField(
            model_name='weldingseam',
            name='wm_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_material_1', to='Process.WeldingMaterial', verbose_name='焊丝/焊条_1_材质'),
        ),
        migrations.AlterField(
            model_name='weldingseam',
            name='wm_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_seam_material_2', to='Process.WeldingMaterial', verbose_name='焊丝/焊条_2_材质'),
        ),
    ]
