# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0019_auto_20171230_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_materials', to='Process.Material', verbose_name='材质'),
        ),
    ]
