# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0020_auto_20171230_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotalist',
            name='status',
            field=models.IntegerField(choices=[(0, '待编制'), (1, '待审核'), (2, '已生成采购物料')], default=0, verbose_name='定额明细表编制状态'),
        ),
    ]
