REVIEW_STATUS_DEFAULT = -1
REVIEW_STATUS_PASS = 0
REVIEW_STATUS_FAIL = 1
REVIEW_STATUS_CHOICES = (
    (REVIEW_STATUS_DEFAULT, '未审核'),
    (REVIEW_STATUS_PASS, '通过'),
    (REVIEW_STATUS_FAIL, '不通过'),
)


BIDDING_DOC_UPLOAD_TO_PROCESS = 0
BIDDING_DOC_UPLOAD_TO_PROCUREMENT = 1
BIDDING_DOC_UPLOAD_TO_PRODUCTION = 2
BIDDING_DOC_UPLOAD_FROM_PROCESS = 3
BIDDING_DOC_UPLOAD_FROM_PROCUREMENT = 4
BIDDING_DOC_UPLOAD_FROM_PRODUCTION = 5

BIDDING_DOC_UPLOAD_TYPE_CHOICES = (
    (BIDDING_DOC_UPLOAD_TO_PROCESS, '经销->工艺'),
    (BIDDING_DOC_UPLOAD_TO_PROCUREMENT, '经销->采购'),
    (BIDDING_DOC_UPLOAD_TO_PRODUCTION, '经销-生产'),
    (BIDDING_DOC_UPLOAD_FROM_PROCESS, '工艺->经销'),
    (BIDDING_DOC_UPLOAD_FROM_PROCUREMENT, '采购->经销'),
    (BIDDING_DOC_UPLOAD_FROM_PRODUCTION, '生产->经销'),
)
