REVIEW_STATUS_DEFAULT = -1
REVIEW_STATUS_PASS = 0
REVIEW_STATUS_FAIL = 1
REVIEW_STATUS_CHOICES = (
    (REVIEW_STATUS_DEFAULT, '未审核'),
    (REVIEW_STATUS_PASS, '通过'),
    (REVIEW_STATUS_FAIL, '不通过'),
)
