# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:29
from __future__ import unicode_literals

import Core.utils.generates
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveDepartmentFileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch', models.BooleanField(default=False, verbose_name='简图')),
                ('pressure_test', models.BooleanField(default=False, verbose_name='试压工艺')),
                ('process_lib', models.BooleanField(default=False, verbose_name='工艺库')),
                ('product_graph', models.BooleanField(default=False, verbose_name='产品图')),
                ('encasement_graph', models.BooleanField(default=False, verbose_name='装箱图')),
                ('shipping_mark', models.BooleanField(default=False, verbose_name='唛头')),
                ('encasement_list', models.BooleanField(default=False, verbose_name='装箱单')),
                ('coating_detail', models.BooleanField(default=False, verbose_name='涂装明细')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='工作令')),
            ],
            options={
                'verbose_name': '综合工部文件清单',
                'verbose_name_plural': '综合工部文件清单',
            },
        ),
        migrations.CreateModel(
            name='ProcessDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.IntegerField(choices=[(0, 'W'), (1, 'W1'), (2, 'W2'), (3, 'W3'), (4, 'W4'), (5, 'W5'), (6, 'W6'), (7, 'W25'), (8, 'P01'), (9, 'P02'), (10, 'R'), (11, 'R1'), (12, 'R2'), (13, 'Z'), (14, 'H'), (15, 'M'), (16, 'L'), (17, 'Y'), (18, 'G'), (19, 'G1'), (20, 'G2'), (21, 'G3'), (22, 'G4'), (23, 'G5'), (24, 'X'), (25, 'J'), (28, 'D'), (27, 'D2'), (26, 'K')], verbose_name='工序')),
                ('process_order', models.IntegerField(verbose_name='工序序号')),
                ('man_hours', models.CharField(blank=True, max_length=20, null=True, verbose_name='工时')),
                ('estimated_start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('estimated_finish_date', models.DateField(blank=True, null=True, verbose_name='计划完成日期')),
                ('actual_finish_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='检查时间')),
                ('inspection_content', models.CharField(blank=True, max_length=500, null=True, verbose_name='检查内容')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='检查者')),
            ],
            options={
                'verbose_name': '工序详细信息',
                'verbose_name_plural': '工序详细信息',
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=Core.utils.generates.gen_uuid, max_length=50, unique=True, verbose_name='生产计划编号')),
                ('status', models.IntegerField(choices=[(-1, '未设置'), (0, '必保'), (1, '在制')], default=1, verbose_name='生产计划状态')),
                ('plan_date', models.DateField(auto_now_add=True, verbose_name='计划年月')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='工作令')),
            ],
            options={
                'verbose_name': '生产计划',
                'verbose_name_plural': '生产计划',
            },
        ),
        migrations.CreateModel(
            name='ProductionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.UserInfo', verbose_name='生产人员')),
            ],
            options={
                'verbose_name': '生产人员',
                'verbose_name_plural': '生产人员',
            },
        ),
        migrations.CreateModel(
            name='ProductionWorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('process', models.IntegerField(choices=[(0, 'W'), (1, 'W1'), (2, 'W2'), (3, 'W3'), (4, 'W4'), (5, 'W5'), (6, 'W6'), (7, 'W25'), (8, 'P01'), (9, 'P02'), (10, 'R'), (11, 'R1'), (12, 'R2'), (13, 'Z'), (14, 'H'), (15, 'M'), (16, 'L'), (17, 'Y'), (18, 'G'), (19, 'G1'), (20, 'G2'), (21, 'G3'), (22, 'G4'), (23, 'G5'), (24, 'X'), (25, 'J'), (28, 'D'), (27, 'D2'), (26, 'K')], verbose_name='工序')),
            ],
            options={
                'verbose_name': '生产工作组',
                'verbose_name_plural': '生产工作组',
            },
        ),
        migrations.CreateModel(
            name='SubMateriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_finish_date', models.DateField(blank=True, null=True, verbose_name='计划完成日期')),
                ('actual_finish_date', models.DateField(blank=True, null=True, verbose_name='实际完成日期')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Materiel', verbose_name='工作票')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='所属工作令')),
            ],
            options={
                'verbose_name': '子工作票',
                'verbose_name_plural': '子工作票',
            },
        ),
        migrations.AddField(
            model_name='productionuser',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Production.ProductionWorkGroup', verbose_name='所属工作组'),
        ),
        migrations.AddField(
            model_name='processdetail',
            name='sub_materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Production.SubMateriel', verbose_name='工作票'),
        ),
        migrations.AddField(
            model_name='processdetail',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Production.ProductionWorkGroup', verbose_name='工作组'),
        ),
        migrations.AlterUniqueTogether(
            name='processdetail',
            unique_together=set([('sub_materiel', 'process_order')]),
        ),
    ]
