# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0007_auto_20171214_1035'),
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetail',
            name='process_step',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessStep', verbose_name='工序步骤'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='工艺物料'),
        ),
        migrations.RemoveField(
            model_name='processdetail',
            name='man_hours',
        ),
        migrations.RemoveField(
            model_name='processdetail',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processdetail',
            name='process_order',
        ),
        migrations.AlterUniqueTogether(
            name='processdetail',
            unique_together=set([('sub_material', 'process_step')]),
        ),
    ]
