# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0002_auto_20171222_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备注'),
        ),
    ]
