# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_productionplan_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdetail',
            name='actual_finish_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间'),
        ),
        migrations.AlterField(
            model_name='processdetail',
            name='estimated_finish_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划完成时间'),
        ),
        migrations.AlterField(
            model_name='processdetail',
            name='estimated_start_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间'),
        ),
        migrations.AlterField(
            model_name='processdetail',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessStep', verbose_name='工序步骤'),
        ),
        migrations.AlterField(
            model_name='submaterial',
            name='actual_finish_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间'),
        ),
        migrations.AlterField(
            model_name='submaterial',
            name='estimated_finish_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划完成时间'),
        ),
    ]
