# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_auto_20171231_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdetail',
            name='status',
            field=models.IntegerField(choices=[(0, '未计划'), (1, '已计划'), (2, '已分配'), (3, '已确认'), (4, '已检查')], default=0, verbose_name='工序详细信息状态'),
        ),
    ]
