# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_processdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplan',
            name='plan_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划年月'),
        ),
    ]
