# 名词解释
# 必保为当月必须完成
# 在制表示当月需要完成一部分工序
PRODUCTION_PLAN_NOTSET = -1
PRODUCTION_PLAN_STRICT = 0
PRODUCTION_PLAN_RELAX = 1
PRODUCTION_PLAN_STATUS_CHOICES = (
    (PRODUCTION_PLAN_NOTSET, '未设置'),
    (PRODUCTION_PLAN_STRICT, '必保'),
    (PRODUCTION_PLAN_RELAX, '在制'),
)

PROCESS_STATUS_NEW = 0
PROCESS_STATUS_PLANED = 1
PROCESS_STATUS_ALLOCATED = 2
PROCESS_STATUS_CONFIRMED = 3
PROCESS_STATUS_CHECKED = 4
PROCESS_STATUS_CHOICES = (
    (PROCESS_STATUS_NEW, '未计划'),
    (PROCESS_STATUS_PLANED, '已计划'),
    (PROCESS_STATUS_ALLOCATED, '已分配'),
    (PROCESS_STATUS_CONFIRMED, '已确认'),
    (PROCESS_STATUS_CHECKED, '已检查'),
)
