# 名词解释
# 必保为当月必须完成
# 在制表示当月需要完成一部分工序
PRODUCTION_PLAN_NOTSET = -1
PRODUCTION_PLAN_STRICT = 0
PRODUCTION_PLAN_RELAX = 1
PRODUCTION_PLAN_STATUS_CHOICES = (
    (PRODUCTION_PLAN_NOTSET, '未设置'),
    (PRODUCTION_PLAN_STRICT, '必保'),
    (PRODUCTION_PLAN_RELAX, '在制'),
)
