SELL_TYPE_DOMESTIC = 0
SELL_TYPE_EXPORT = 1
SELL_TYPES = (
    (SELL_TYPE_DOMESTIC, '内销'),
    (SELL_TYPE_EXPORT, '外销'),
)

OTHER = 0
WELD_ROD = 1
WELD_WIRE = 2
WELD_RIBBON = 3
WELD_FLUX = 4
SHEET = 5
PROFILE = 6
PURCHASED = 7
AUXILIARY_TOOL = 8
MATERIAL_CATEGORY_CHOICES = (
    (WELD_ROD, '焊条'),
    (WELD_WIRE, '焊丝'),
    (WELD_RIBBON, '焊带'),
    (WELD_FLUX, '焊剂'),
    (SHEET, '板材'),
    (PROFILE, '型材'),
    (PURCHASED, '外购件'),
    (AUXILIARY_TOOL, '辅助工具'),
    (OTHER, '其他'),
)

GENDER_MALE = 0
GENDER_FEMALE = 1

GENDER_CHOICES = (
    (GENDER_MALE, '男'),
    (GENDER_FEMALE, '女'),
)
