# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:21
from __future__ import unicode_literals

import Core.utils.hash
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSteelMaterialRefundDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('specification', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='重量')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliaryMaterialApplyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='领用单位')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='填写时间')),
                ('status', models.IntegerField(choices=[(0, '领用已创建'), (1, '领用已审核'), (2, '领用已检查'), (3, '领用已发料'), (4, '领用已完成'), (-1, '领用已终止')], default=0, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '辅材领用单',
                'verbose_name_plural': '辅材领用单',
            },
        ),
        migrations.CreateModel(
            name='AuxiliaryMaterialApplyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_count', models.IntegerField(verbose_name='申请数量')),
                ('actual_count', models.IntegerField(blank=True, null=True, verbose_name='实发数量')),
            ],
            options={
                'verbose_name': '辅材领用单明细',
                'verbose_name_plural': '辅材领用单明细',
            },
        ),
        migrations.CreateModel(
            name='AuxiliaryMaterialEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('source', models.CharField(max_length=20, verbose_name='货物来源')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('status', models.IntegerField(choices=[(0, '待采购员确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '辅助材料入库单',
                'verbose_name_plural': '辅助材料入库单',
            },
        ),
        migrations.CreateModel(
            name='AuxiliaryMaterialEntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='单重')),
                ('count', models.FloatField(verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('factory', models.CharField(blank=True, default='', max_length=100, verbose_name='厂家')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '辅材入库单明细',
                'verbose_name_plural': '辅材入库单明细',
            },
        ),
        migrations.CreateModel(
            name='AuxiliaryMaterialInventoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '正常使用'), (1, '已用尽'), (2, '已过期'), (3, '已报废')], default=0, verbose_name='状态')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='单重')),
                ('count', models.FloatField(blank=True, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
            ],
            options={
                'verbose_name': '辅材库存明细',
                'verbose_name_plural': '辅材库存明细',
            },
        ),
        migrations.CreateModel(
            name='BoughtInComponentApplyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='领用单位')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='填写时间')),
                ('status', models.IntegerField(choices=[(0, '领用已创建'), (1, '领用已审核'), (2, '领用已检查'), (3, '领用已发料'), (4, '领用已完成'), (-1, '领用已终止')], default=0, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('revised_number', models.CharField(blank=True, default='', max_length=50, verbose_name='修订号')),
                ('sample_report', models.CharField(blank=True, default='', max_length=50, verbose_name='样表')),
            ],
            options={
                'verbose_name': '外购件领用单',
                'verbose_name_plural': '外购件领用单',
            },
        ),
        migrations.CreateModel(
            name='BoughtInComponentApplyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '外购件领用单明细',
                'verbose_name_plural': '外购件领用单明细',
            },
        ),
        migrations.CreateModel(
            name='BoughtInComponentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('source', models.CharField(max_length=20, verbose_name='货物来源')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('status', models.IntegerField(choices=[(0, '待采购员确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('category', models.IntegerField(choices=[(0, '外协加工'), (1, '标准件'), (2, '锻件')], verbose_name='外购件类型')),
            ],
            options={
                'verbose_name': '外购件入库单',
                'verbose_name_plural': '外购件入库单',
            },
        ),
        migrations.CreateModel(
            name='BoughtInComponentEntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='单重')),
                ('count', models.FloatField(verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('factory', models.CharField(blank=True, default='', max_length=100, verbose_name='厂家')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '外购件入库单明细',
                'verbose_name_plural': '外购件入库单明细',
            },
        ),
        migrations.CreateModel(
            name='BoughtInComponentInventoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '正常使用'), (1, '已用尽'), (2, '已过期'), (3, '已报废')], default=0, verbose_name='状态')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='单重')),
                ('count', models.FloatField(blank=True, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('category', models.IntegerField(choices=[(0, '外协加工'), (1, '标准件'), (2, '锻件')], default=0, verbose_name='外购件类型')),
            ],
            options={
                'verbose_name': '外购件库存明细',
                'verbose_name_plural': '外购件库存明细',
            },
        ),
        migrations.CreateModel(
            name='BoughtInComponentRefundCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.IntegerField(choices=[(0, '退库人'), (1, '检查员'), (2, '库管员'), (3, '结束'), (-1, '终止')], default=0, verbose_name='退库单状态')),
            ],
            options={
                'verbose_name': '外购件退库单',
                'verbose_name_plural': '外购件退库单',
            },
        ),
        migrations.CreateModel(
            name='BoughtInComponentRefundDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '外购件退库单明细',
                'verbose_name_plural': '外购件退库单明细',
            },
        ),
        migrations.CreateModel(
            name='InventoryTerminationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('category', models.IntegerField(choices=[(0, '入库单'), (1, '领用单'), (2, '退库单')], verbose_name='单据类型')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='单据ID')),
                ('reason', models.CharField(max_length=200, verbose_name='原因')),
            ],
            options={
                'verbose_name': '库存单据终止记录',
                'verbose_name_plural': '库存单据终止记录',
            },
        ),
        migrations.CreateModel(
            name='SteelMaterialApplyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='领用单位')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='填写时间')),
                ('status', models.IntegerField(choices=[(0, '领用已创建'), (1, '领用已审核'), (2, '领用已检查'), (3, '领用已发料'), (4, '领用已完成'), (-1, '领用已终止')], default=0, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '钢材领用单',
                'verbose_name_plural': '钢材领用单',
            },
        ),
        migrations.CreateModel(
            name='SteelMaterialApplyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_mark', models.CharField(max_length=20, verbose_name='钢号')),
                ('material_code', models.CharField(max_length=20, verbose_name='材质编号')),
                ('specification', models.CharField(max_length=50, verbose_name='规格')),
                ('count', models.IntegerField(verbose_name='申请数量')),
                ('component', models.CharField(blank=True, max_length=100, null=True, verbose_name='零件编号')),
            ],
            options={
                'verbose_name': '钢材领用单明细',
                'verbose_name_plural': '钢材领用单明细',
            },
        ),
        migrations.CreateModel(
            name='SteelMaterialEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('source', models.CharField(max_length=20, verbose_name='货物来源')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('status', models.IntegerField(choices=[(0, '待采购员确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('steel_type', models.IntegerField(choices=[(0, '板材'), (1, '型材')], verbose_name='材料类型')),
            ],
            options={
                'verbose_name': '钢材入库单',
                'verbose_name_plural': '钢材入库单',
            },
        ),
        migrations.CreateModel(
            name='SteelMaterialEntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='单重')),
                ('count', models.FloatField(verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('factory', models.CharField(blank=True, default='', max_length=100, verbose_name='厂家')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('length', models.FloatField(verbose_name='长度')),
            ],
            options={
                'verbose_name': '钢材入库单明细',
                'verbose_name_plural': '钢材入库单明细',
            },
        ),
        migrations.CreateModel(
            name='SteelMaterialInventoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '正常使用'), (1, '已用尽'), (2, '已过期'), (3, '已报废')], default=0, verbose_name='状态')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='单重')),
                ('count', models.FloatField(blank=True, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('length', models.FloatField(verbose_name='长度')),
                ('refund_times', models.IntegerField(default=0, verbose_name='退库次数')),
            ],
            options={
                'verbose_name': '钢材库存明细',
                'verbose_name_plural': '钢材库存明细',
            },
        ),
        migrations.CreateModel(
            name='SteelMaterialRefundCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.IntegerField(choices=[(0, '退库人'), (1, '检查员'), (2, '库管员'), (3, '结束'), (-1, '终止')], default=0, verbose_name='退库单状态')),
            ],
            options={
                'verbose_name': '钢材退库单',
                'verbose_name_plural': '钢材退库单',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='库房名称')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='位置')),
                ('category', models.IntegerField(choices=[(0, '焊材'), (1, '钢材'), (2, '辅材'), (3, '外购件')], verbose_name='库存类型')),
            ],
            options={
                'verbose_name': '库房',
                'verbose_name_plural': '库房',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialApplyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='领用单位')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='填写时间')),
                ('status', models.IntegerField(choices=[(0, '领用已创建'), (1, '领用已审核'), (2, '领用已检查'), (3, '领用已发料'), (4, '领用已完成'), (-1, '领用已终止')], default=0, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '焊材领用单',
                'verbose_name_plural': '焊材领用单',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialApplyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weld_seam_uid', models.CharField(blank=True, max_length=20, null=True, verbose_name='焊缝编号')),
                ('material_mark', models.CharField(max_length=50, verbose_name='焊材牌号')),
                ('model_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='型号')),
                ('specification', models.CharField(max_length=20, verbose_name='规格')),
                ('material_code', models.CharField(blank=True, default='', max_length=20, verbose_name='材质标记')),
                ('apply_weight', models.FloatField(verbose_name='领用重量')),
                ('apply_count', models.FloatField(verbose_name='领用数量')),
                ('actual_weight', models.FloatField(blank=True, null=True, verbose_name='实发重量')),
                ('actual_count', models.FloatField(blank=True, null=True, verbose_name='实发数量')),
            ],
            options={
                'verbose_name': '焊材领用单明细',
                'verbose_name_plural': '焊材领用单明细',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialBakeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('standard_num', models.CharField(blank=True, default='', max_length=50, verbose_name='标准号')),
                ('size', models.CharField(blank=True, default='', max_length=50, verbose_name='规格')),
                ('class_num', models.CharField(max_length=50, verbose_name='牌号')),
                ('heat_num', models.CharField(max_length=50, verbose_name='炉批号')),
                ('codedmark', models.CharField(blank=True, default='', max_length=50, verbose_name='编码标记')),
                ('quantity', models.FloatField(default=0, verbose_name='数量')),
                ('furnace_time', models.DateTimeField(blank=True, default='', verbose_name='进炉时间')),
                ('baking_temp', models.FloatField(default=0, verbose_name='烘焙温度')),
                ('heating_time', models.DateTimeField(blank=True, default='', verbose_name='到达温度时间')),
                ('cooling_time', models.DateTimeField(blank=True, default='', verbose_name='降温时间')),
                ('holding_time', models.DateTimeField(blank=True, default='', verbose_name='进保湿炉时间')),
                ('holding_temp', models.FloatField(default=0, verbose_name='保温温度')),
                ('apply_time', models.DateTimeField(blank=True, default='', verbose_name='领用时间')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '焊材烘焙记录卡',
                'verbose_name_plural': '焊材烘焙记录卡',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('source', models.CharField(max_length=20, verbose_name='货物来源')),
                ('create_dt', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('status', models.IntegerField(choices=[(0, '待采购员确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '焊材入库单',
                'verbose_name_plural': '焊材入库单',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialEntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='单重')),
                ('count', models.FloatField(verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('factory', models.CharField(blank=True, default='', max_length=100, verbose_name='厂家')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='出厂日期')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.WeldingMaterialEntry', verbose_name='入库单')),
            ],
            options={
                'verbose_name': '焊材入库单明细',
                'verbose_name_plural': '焊材入库单明细',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialHumitureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('actual_temp_1', models.FloatField(verbose_name='实际温度(10:00)')),
                ('actual_humid_1', models.FloatField(verbose_name='实际湿度(10:00)')),
                ('actual_temp_2', models.FloatField(verbose_name='实际温度(16:00)')),
                ('actual_humid_2', models.FloatField(verbose_name='实际湿度(16:00)')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '焊材库温湿度记录卡',
                'verbose_name_plural': '焊材库温湿度记录卡',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialInventoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '正常使用'), (1, '已用尽'), (2, '已过期'), (3, '已报废')], default=0, verbose_name='状态')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='单重')),
                ('count', models.FloatField(blank=True, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('deadline', models.DateField(verbose_name='有效期')),
                ('entry_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.WeldingMaterialEntryDetail', verbose_name='焊材入库明细')),
            ],
            options={
                'verbose_name': '焊材库存明细',
                'verbose_name_plural': '焊材库存明细',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialRefundCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.IntegerField(choices=[(0, '退库人'), (1, '检查员'), (2, '库管员'), (3, '结束'), (-1, '终止')], default=0, verbose_name='退库单状态')),
                ('apply_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.WeldingMaterialApplyCard', verbose_name='领用单')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialrefundcard_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检查员')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialrefundcard_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员')),
                ('refunder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialrefundcard_refunder', to=settings.AUTH_USER_MODEL, verbose_name='退料人')),
            ],
            options={
                'verbose_name': '焊材退库单',
                'verbose_name_plural': '焊材退库单',
            },
        ),
        migrations.CreateModel(
            name='WeldingMaterialRefundDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='退库量（重量）')),
                ('count', models.FloatField(blank=True, null=True, verbose_name='退库量（数量）')),
                ('apply_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.WeldingMaterialApplyDetail', verbose_name='领用明细')),
                ('refund_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.WeldingMaterialRefundCard', verbose_name='退库单')),
            ],
            options={
                'verbose_name': '焊材退库单明细',
                'verbose_name_plural': '焊材退库单明细',
            },
        ),
        migrations.CreateModel(
            name='WeldingWarehouseThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=50, verbose_name='规格')),
                ('count', models.FloatField(verbose_name='数量')),
                ('category', models.IntegerField(choices=[(0, '焊条'), (1, '焊丝'), (2, '焊带'), (3, '焊剂'), (5, '板材'), (6, '型材'), (7, '外购件'), (10, '辅材'), (8, '其他')], verbose_name='材料种类')),
            ],
            options={
                'verbose_name': '焊材库存安全量',
                'verbose_name_plural': '焊材库存安全量',
            },
        ),
        migrations.CreateModel(
            name='BarSteelMaterialRefundDetail',
            fields=[
                ('abstractsteelmaterialrefunddetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.AbstractSteelMaterialRefundDetail')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='退库长度')),
            ],
            options={
                'verbose_name': '型材退库单明细',
                'verbose_name_plural': '型材退库单明细',
            },
            bases=('Inventory.abstractsteelmaterialrefunddetail',),
        ),
        migrations.CreateModel(
            name='BoardSteelMaterialRefundDetail',
            fields=[
                ('abstractsteelmaterialrefunddetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Inventory.AbstractSteelMaterialRefundDetail')),
                ('graph_path', models.FileField(blank=True, null=True, upload_to=Core.utils.hash.DynamicHashPath('BoardSteelMaterialRefundDetail'), verbose_name='套料图')),
            ],
            options={
                'verbose_name': '板材退库单明细',
                'verbose_name_plural': '板材退库单明细',
            },
            bases=('Inventory.abstractsteelmaterialrefunddetail',),
        ),
    ]
