# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Procurement', '0001_initial'),
        ('Inventory', '0001_initial'),
        ('Core', '0002_auto_20171206_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='weldingmaterialentrydetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='weldingmaterialentry',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AddField(
            model_name='weldingmaterialentry',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialentry_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检验员'),
        ),
        migrations.AddField(
            model_name='weldingmaterialentry',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialentry_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='weldingmaterialentry',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialentry_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AddField(
            model_name='weldingmaterialbakerecord',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welding_bake_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='weldingmaterialbakerecord',
            name='welding_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welding_bake_engineer', to=settings.AUTH_USER_MODEL, verbose_name='焊接工程师'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplydetail',
            name='apply_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.WeldingMaterialApplyCard', verbose_name='领用单'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplydetail',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.WeldingMaterialInventoryDetail', verbose_name='库存明细'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialapplycard_applicant', to=settings.AUTH_USER_MODEL, verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialapplycard_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialapplycard_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检查员'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weldingmaterialapplycard_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='sub_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='子工作令'),
        ),
        migrations.AddField(
            model_name='steelmaterialrefundcard',
            name='apply_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.SteelMaterialApplyCard', verbose_name='领用单'),
        ),
        migrations.AddField(
            model_name='steelmaterialrefundcard',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialrefundcard_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检查员'),
        ),
        migrations.AddField(
            model_name='steelmaterialrefundcard',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialrefundcard_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='steelmaterialrefundcard',
            name='refunder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialrefundcard_refunder', to=settings.AUTH_USER_MODEL, verbose_name='退料人'),
        ),
        migrations.AddField(
            model_name='steelmaterialinventorydetail',
            name='entry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.SteelMaterialEntryDetail', verbose_name='钢材入库明细'),
        ),
        migrations.AddField(
            model_name='steelmaterialinventorydetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.Warehouse', verbose_name='库房位置'),
        ),
        migrations.AddField(
            model_name='steelmaterialentrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.SteelMaterialEntry', verbose_name='入库单'),
        ),
        migrations.AddField(
            model_name='steelmaterialentrydetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='steelmaterialentry',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AddField(
            model_name='steelmaterialentry',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialentry_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检验员'),
        ),
        migrations.AddField(
            model_name='steelmaterialentry',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialentry_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='steelmaterialentry',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialentry_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplydetail',
            name='apply_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.SteelMaterialApplyCard', verbose_name='领用单'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplydetail',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.SteelMaterialInventoryDetail', verbose_name='库存明细'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplydetail',
            name='sub_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='子工作令'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplycard',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialapplycard_applicant', to=settings.AUTH_USER_MODEL, verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplycard',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialapplycard_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplycard',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialapplycard_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检查员'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplycard',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steelmaterialapplycard_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplycard',
            name='sub_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='子工作令'),
        ),
        migrations.AddField(
            model_name='inventoryterminationrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='boughtincomponentrefunddetail',
            name='apply_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.BoughtInComponentApplyDetail', verbose_name='领用明细'),
        ),
        migrations.AddField(
            model_name='boughtincomponentrefunddetail',
            name='refund_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.BoughtInComponentRefundCard', verbose_name='退库单'),
        ),
        migrations.AddField(
            model_name='boughtincomponentrefundcard',
            name='apply_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.BoughtInComponentApplyCard', verbose_name='领用单'),
        ),
        migrations.AddField(
            model_name='boughtincomponentrefundcard',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponentrefundcard_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检查员'),
        ),
        migrations.AddField(
            model_name='boughtincomponentrefundcard',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponentrefundcard_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='boughtincomponentrefundcard',
            name='refunder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponentrefundcard_refunder', to=settings.AUTH_USER_MODEL, verbose_name='退料人'),
        ),
        migrations.AddField(
            model_name='boughtincomponentinventorydetail',
            name='entry_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventory.BoughtInComponentEntryDetail', verbose_name='外购件入库明细'),
        ),
        migrations.AddField(
            model_name='boughtincomponententrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.BoughtInComponentEntry', verbose_name='入库单'),
        ),
        migrations.AddField(
            model_name='boughtincomponententrydetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='boughtincomponententry',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AddField(
            model_name='boughtincomponententry',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponententry_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检验员'),
        ),
        migrations.AddField(
            model_name='boughtincomponententry',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponententry_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='boughtincomponententry',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponententry_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplydetail',
            name='apply_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.BoughtInComponentApplyCard', verbose_name='领用单'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplydetail',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.BoughtInComponentInventoryDetail', verbose_name='库存明细'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplycard',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponentapplycard_applicant', to=settings.AUTH_USER_MODEL, verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplycard',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponentapplycard_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplycard',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponentapplycard_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检查员'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplycard',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtincomponentapplycard_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplycard',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplycard',
            name='sub_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='子工作令'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialinventorydetail',
            name='entry_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.AuxiliaryMaterialEntryDetail', verbose_name='辅材入库明细'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialentrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.AuxiliaryMaterialEntry', verbose_name='入库单'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialentrydetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialentry',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialentry',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliarymaterialentry_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检验员'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialentry',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliarymaterialentry_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialentry',
            name='purchaser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliarymaterialentry_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplydetail',
            name='actual_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_inventory', to='Inventory.AuxiliaryMaterialInventoryDetail', verbose_name='实发材料'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplydetail',
            name='apply_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.AuxiliaryMaterialApplyCard', verbose_name='领用单'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplydetail',
            name='apply_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_inventory', to='Inventory.AuxiliaryMaterialInventoryDetail', verbose_name='库存明细'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplycard',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliarymaterialapplycard_applicant', to=settings.AUTH_USER_MODEL, verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplycard',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliarymaterialapplycard_auditor', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplycard',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliarymaterialapplycard_inspector', to=settings.AUTH_USER_MODEL, verbose_name='检查员'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplycard',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliarymaterialapplycard_keeper', to=settings.AUTH_USER_MODEL, verbose_name='库管员'),
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplycard',
            name='sub_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='子工作令'),
        ),
        migrations.AddField(
            model_name='abstractsteelmaterialrefunddetail',
            name='apply_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.SteelMaterialApplyDetail', verbose_name='领用明细'),
        ),
        migrations.AddField(
            model_name='abstractsteelmaterialrefunddetail',
            name='refund_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.SteelMaterialRefundCard', verbose_name='退库单'),
        ),
    ]
