# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliarymaterialapplycard',
            name='status',
            field=models.IntegerField(choices=[(0, '待领用确认'), (1, '待审核确认'), (2, '待检查确认'), (3, '待库管确认'), (4, '领用完成'), (-1, '领用终止')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='auxiliarymaterialentry',
            name='status',
            field=models.IntegerField(choices=[(0, '待采购确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态'),
        ),
        migrations.AlterField(
            model_name='boughtincomponentapplycard',
            name='status',
            field=models.IntegerField(choices=[(0, '待领用确认'), (1, '待审核确认'), (2, '待检查确认'), (3, '待库管确认'), (4, '领用完成'), (-1, '领用终止')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='boughtincomponententry',
            name='status',
            field=models.IntegerField(choices=[(0, '待采购确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态'),
        ),
        migrations.AlterField(
            model_name='steelmaterialapplycard',
            name='status',
            field=models.IntegerField(choices=[(0, '待领用确认'), (1, '待审核确认'), (2, '待检查确认'), (3, '待库管确认'), (4, '领用完成'), (-1, '领用终止')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='steelmaterialentry',
            name='status',
            field=models.IntegerField(choices=[(0, '待采购确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态'),
        ),
        migrations.AlterField(
            model_name='weldingmaterialapplycard',
            name='status',
            field=models.IntegerField(choices=[(0, '待领用确认'), (1, '待审核确认'), (2, '待检查确认'), (3, '待库管确认'), (4, '领用完成'), (-1, '领用终止')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='weldingmaterialentry',
            name='status',
            field=models.IntegerField(choices=[(0, '待采购确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '入库完成'), (-1, '入库终止')], default=0, verbose_name='入库单状态'),
        ),
    ]
