# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingmaterialentrydetail',
            name='production_date',
        ),
        migrations.AddField(
            model_name='weldingmaterialentrydetail',
            name='production_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='出厂日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weldingmaterialinventorydetail',
            name='deadline',
            field=models.DateTimeField(verbose_name='有效期'),
        ),
    ]
