# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtincomponentrefunddetail',
            name='refund_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Inventory.BoughtInComponentRefundCard', verbose_name='退库单'),
        ),
    ]
