# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0002_auto_20171215_1431'),
        ('Inventory', '0002_auto_20171206_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weldingmaterialapplydetail',
            name='apply_card',
        ),
        migrations.RemoveField(
            model_name='weldingmaterialapplydetail',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='weldingmaterialrefunddetail',
            name='apply_detail',
        ),
        migrations.RemoveField(
            model_name='weldingmaterialrefunddetail',
            name='refund_card',
        ),
        migrations.RenameField(
            model_name='boughtincomponentinventorydetail',
            old_name='entry_item',
            new_name='entry_detail',
        ),
        migrations.RemoveField(
            model_name='auxiliarymaterialapplycard',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='boughtincomponentapplycard',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='boughtincomponentapplycard',
            name='material',
        ),
        migrations.RemoveField(
            model_name='boughtincomponentinventorydetail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='steelmaterialapplycard',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='weldingmaterialapplycard',
            name='create_date',
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplycard',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='填写时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auxiliarymaterialapplydetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='boughtincomponentapplycard',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='填写时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boughtincomponentapplydetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='steelmaterialapplycard',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='填写时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steelmaterialapplydetail',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='actual_count',
            field=models.FloatField(blank=True, null=True, verbose_name='实发数量'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='actual_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='实发重量'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='apply_count',
            field=models.FloatField(default=0, verbose_name='领用数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='apply_weight',
            field=models.FloatField(default=0, verbose_name='领用重量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='填写时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.WeldingMaterialInventoryDetail', verbose_name='库存明细'),
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.ProcurementMaterial', verbose_name='采购物料'),
        ),
        migrations.AddField(
            model_name='weldingmaterialrefundcard',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='退库量（数量）'),
        ),
        migrations.AddField(
            model_name='weldingmaterialrefundcard',
            name='weight',
            field=models.FloatField(default=0, verbose_name='退库量（重量）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='steelmaterialinventorydetail',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.Warehouse', verbose_name='库房'),
        ),
        migrations.DeleteModel(
            name='WeldingMaterialApplyDetail',
        ),
        migrations.DeleteModel(
            name='WeldingMaterialRefundDetail',
        ),
    ]
