# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20171227_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtincomponentrefundcard',
            name='status',
            field=models.IntegerField(choices=[(0, '待退库确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '退库完成'), (-1, '退库终止')], default=0, verbose_name='退库单状态'),
        ),
        migrations.AlterField(
            model_name='steelmaterialrefundcard',
            name='status',
            field=models.IntegerField(choices=[(0, '待退库确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '退库完成'), (-1, '退库终止')], default=0, verbose_name='退库单状态'),
        ),
        migrations.AlterField(
            model_name='weldingmaterialrefundcard',
            name='status',
            field=models.IntegerField(choices=[(0, '待退库确认'), (1, '待检查确认'), (2, '待库管确认'), (3, '退库完成'), (-1, '退库终止')], default=0, verbose_name='退库单状态'),
        ),
    ]
