# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20171216_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliarymaterialentry',
            options={'verbose_name': '辅材入库单', 'verbose_name_plural': '辅材入库单'},
        ),
        migrations.AlterField(
            model_name='auxiliarymaterialentrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Inventory.AuxiliaryMaterialEntry', verbose_name='入库单'),
        ),
        migrations.AlterField(
            model_name='boughtincomponententrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Inventory.BoughtInComponentEntry', verbose_name='入库单'),
        ),
        migrations.AlterField(
            model_name='steelmaterialentrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Inventory.SteelMaterialEntry', verbose_name='入库单'),
        ),
        migrations.AlterField(
            model_name='weldingmaterialentrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Inventory.WeldingMaterialEntry', verbose_name='入库单'),
        ),
    ]
