# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20171219_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steelmaterialapplydetail',
            name='sub_order',
        ),
    ]
