# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Process', '0015_auto_20171223_0925'),
        ('Inventory', '0003_remove_steelmaterialapplydetail_sub_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boughtincomponentapplydetail',
            name='procurement_material',
        ),
        migrations.RemoveField(
            model_name='steelmaterialapplydetail',
            name='procurement_material',
        ),
        migrations.RemoveField(
            model_name='weldingmaterialapplycard',
            name='procurement_material',
        ),
        migrations.AddField(
            model_name='boughtincomponentapplydetail',
            name='process_material',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='工艺物料'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steelmaterialapplydetail',
            name='process_material',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='工艺物料'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weldingmaterialapplycard',
            name='process_material',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='工艺物料'),
            preserve_default=False,
        ),
    ]
