# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20171227_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steelmaterialentrydetail',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='长度'),
        ),
        migrations.AlterField(
            model_name='weldingmaterialentrydetail',
            name='production_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出厂日期'),
        ),
    ]
