MESSAGE_CATEGORY_NEWS = 0
MESSAGE_CATEGORY_ANNOUNCEMENT = 1
MESSAGE_CATEGORY_PERSONAL = 2

MESSAGE_CATEGORY_CHOICES = (
    (MESSAGE_CATEGORY_NEWS, '公司新闻'),
    (MESSAGE_CATEGORY_ANNOUNCEMENT, '重要通知'),
    (MESSAGE_CATEGORY_PERSONAL, '个人消息'),
)
