BIDDING_SHEET_STATUS_CREATE = 0
BIDDING_SHEET_STATUS_SELECT_SUPPLIER = 1
BIDDING_SHEET_STATUS_INVITE_BID = 2
BIDDING_SHEET_STATUS_PROCESS_FOLLOW = 3
BIDDING_SHEET_STATUS_CHECK_STORE = 4
BIDDING_SHEET_STATUS_COMPLETE = 5
BIDDING_SHEET_STATUS_STOP = 6

BIDDING_SHEET_STATUS_CHOICES = (
    (BIDDING_SHEET_STATUS_CREATE, '标单生成'),
    (BIDDING_SHEET_STATUS_SELECT_SUPPLIER, '供应商选择'),
    (BIDDING_SHEET_STATUS_INVITE_BID, '招标'),
    (BIDDING_SHEET_STATUS_PROCESS_FOLLOW, '过程跟踪'),
    (BIDDING_SHEET_STATUS_CHECK_STORE, '检查入库'),
    (BIDDING_SHEET_STATUS_COMPLETE, '标单完成'),
    (BIDDING_SHEET_STATUS_STOP, '标单终止'),
)

BIDDING_SHEET_PART_STATUS_CREATE = 0
# BIDDING_SHEET_PART_STATUS_ESTABLISHMENT = 1
# BIDDING_SHEET_PART_STATUS_APPROVED = 2
BIDDING_SHEET_PART_STATUS_SELECT_SUPPLLER_APPROVED = 3
BIDDING_SHEET_PART_STATUS_INVITE_BID_APPLY_SELECT = 4
BIDDING_SHEET_PART_STATUS_INVITE_BID_FILL = 5
BIDDING_SHEET_PART_STATUS_INVITE_BID_CARRY = 6
BIDDING_SHEET_PART_STATUS_INVITE_BID_COMPLETE = 7
BIDDING_SHEET_PART_STATUS_PROCESS_FOLLOW = 8
BIDDING_SHEET_PART_STATUS_CHECK = 9
BIDDING_SHEET_PART_STATUS_STORE = 10
BIDDING_SHEET_PART_STATUS_COMPLETE = 11
BIDDING_SHEET_PART_STATUS_STOP = 12

BIDDING_SHEET_PART_STATUS_CHOICES = (
    (BIDDING_SHEET_PART_STATUS_CREATE, '标单创建'),
    # (BIDDING_SHEET_PART_STATUS_ESTABLISHMENT, '标单编制'),
    # (BIDDING_SHEET_PART_STATUS_APPROVED, '标单审批'),
    (BIDDING_SHEET_PART_STATUS_SELECT_SUPPLLER_APPROVED, '供应商选择'),
    (BIDDING_SHEET_PART_STATUS_INVITE_BID_APPLY_SELECT, '招标申请选择'),
    (BIDDING_SHEET_PART_STATUS_INVITE_BID_FILL, '招标申请填写'),
    (BIDDING_SHEET_PART_STATUS_INVITE_BID_CARRY, '招标中'),
    (BIDDING_SHEET_PART_STATUS_INVITE_BID_COMPLETE, '中标确认'),
    (BIDDING_SHEET_PART_STATUS_PROCESS_FOLLOW, '进程跟踪'),
    (BIDDING_SHEET_PART_STATUS_CHECK, '标单检验'),
    (BIDDING_SHEET_PART_STATUS_STORE, '标单入库'),
    (BIDDING_SHEET_PART_STATUS_COMPLETE, '标单完成'),
    (BIDDING_SHEET_PART_STATUS_STOP, '标单终止'),
)

PURCHASE_ORDER_STATUS_BEGIN = 0
PURCHASE_ORDER_STATUS_ESTABLISHMENT = 1
PURCHASE_ORDER_STATUS_AUDIT = 2
PURCHASE_ORDER_STATUS_APPROVED = 3
PURCHASE_ORDER_STATUS_FINISH = 4

PURCHASE_ORDER_STATUS_CHOICES = (
    (PURCHASE_ORDER_STATUS_BEGIN, '创建中订购单'),
    (PURCHASE_ORDER_STATUS_ESTABLISHMENT, '创建完成订购单'),
    (PURCHASE_ORDER_STATUS_AUDIT, '审核通过订购单'),
    (PURCHASE_ORDER_STATUS_APPROVED, '批准通过订购单'),
    (PURCHASE_ORDER_STATUS_FINISH, '已终止历史订购单'),
)

IMPLEMENT_CLASS_TENDER = 0
IMPLEMENT_CLASS_NEGOTIATION = 1

IMPLEMENT_CLASS_CHOICES = (
    (IMPLEMENT_CLASS_TENDER, '招标'),
    (IMPLEMENT_CLASS_NEGOTIATION, '议标'),
)

INVENTORY_TYPE_NOTSET = -1
INVENTORY_TYPE_MAIN_MATERIEL = 0
INVENTORY_TYPE_AUXILIARY_MATERIEL = 1
INVENTORY_TYPE_FIRST_FEEDING = 2
INVENTORY_TYPE_OUT_PURCHASED = 3
INVENTORY_TYPE_WELD_MATERIAL = 4
INVENTORY_TYPE_COOPERANT = 5

INVENTORY_TYPE = (
    (INVENTORY_TYPE_NOTSET, '未设置'),
    (INVENTORY_TYPE_MAIN_MATERIEL, '主材定额'),
    (INVENTORY_TYPE_AUXILIARY_MATERIEL, '辅材定额'),
    (INVENTORY_TYPE_FIRST_FEEDING, '先投件明细'),
    (INVENTORY_TYPE_OUT_PURCHASED, '外购件明细'),
    (INVENTORY_TYPE_WELD_MATERIAL, '焊材定额'),
    (INVENTORY_TYPE_COOPERANT, '工序性外协明细')
)

BID_APPLY_TYPE_APPLY = 1
BID_APPLY_TYPE_SUPPLIER_CHECK = 2
BID_APPLY_TYPE_QUALITYPRICECARD = 3
BID_APPLY_TYPE_MATERIEL_SUBSTITUDE = 4

BID_APPLY_TYPE_CHOICES = (
    (BID_APPLY_TYPE_APPLY, '招标申请表'),
    (BID_APPLY_TYPE_SUPPLIER_CHECK, '供应商审核表'),
    (BID_APPLY_TYPE_QUALITYPRICECARD, '比质比价卡'),
    (BID_APPLY_TYPE_MATERIEL_SUBSTITUDE, '材料代用表'),
)

# TODO: Review names
COMMENT_STATUS_APPLY_FILL = 0
COMMENT_STATUS_APPLY_OPERATOR_COMMENT = 1
COMMENT_STATUS_APPLY_LEAD_COMMENT = 2
COMMENT_STATUS_APPLY_NEED_COMMENT = 3
COMMENT_STATUS_APPLY_CENTRALIZE_COMMENT = 4
COMMENT_STATUS_APPLY_LOGISTICAL_COMMENT = 5
COMMENT_STATUS_APPLY_COMPANY_COMMENT = 6
COMMENT_STATUS_CHECK_FILL = 7
COMMENT_STATUS_CHECK_OPERATOR_COMMENT = 8
COMMENT_STATUS_CHECK_LEAD_COMMENT = 9
COMMENT_STATUS_CHECK_QUALITY_COMMENT = 10
COMMENT_STATUS_CHECK_ECONOMIC_COMMENT = 11
COMMENT_STATUS_CHECK_COMPREHENSIVE_COMMENT = 12
COMMENT_STATUS_QUALITY_FILL = 13
COMMENT_STATUS_QUALITY_OPERATOR_COMMENT = 14
COMMENT_STATUS_QUALITY_NEED_TECH_COMMENT = 15
COMMENT_STATUS_QUALITY_NEED_LEAD_COMMENT = 16
COMMENT_STATUS_QUALITY_COMPREHENSIVE_COMMENT = 17
COMMENT_STATUS_QUALITY_COMPANY_COMMENT = 18
COMMENT_STATUS_APPLY_FINISH = 19
COMMENT_STATUS_MATERIEL_SUBSTITUDE_FILL = 20
COMMENT_STATUS_MATERIEL_SUBSTITUDE_MATERIEL = 21
COMMENT_STATUS_MATERIEL_SUBSTITUDE_PROCESS = 22
COMMENT_STATUS_MATERIEL_SUBSTITUDE_WELDING = 23
COMMENT_STATUS_MATERIEL_SUBSTITUDE_DESIGN = 24
COMMENT_STATUS_MATERIEL_SUBSTITUDE_ORIGINAL = 25
COMMENT_STATUS_MATERIEL_SUBSTITUDE_FINISH = 26

COMMENT_STATUS_CHOICES = (
    (COMMENT_STATUS_APPLY_FILL, '申请表填写'),
    (COMMENT_STATUS_APPLY_OPERATOR_COMMENT, '申请经办人意见'),
    (COMMENT_STATUS_APPLY_LEAD_COMMENT, '申请表申请领导意见'),
    (COMMENT_STATUS_APPLY_NEED_COMMENT, '申请表需求部门意见'),
    (COMMENT_STATUS_APPLY_CENTRALIZE_COMMENT, '申请表归口部门意见'),
    (COMMENT_STATUS_APPLY_LOGISTICAL_COMMENT, '申请表物流采控部门意见'),
    (COMMENT_STATUS_APPLY_COMPANY_COMMENT, '申请表公司意见'),
    (COMMENT_STATUS_CHECK_FILL, '审核表填写'),
    (COMMENT_STATUS_CHECK_OPERATOR_COMMENT, '审核表经办人意见'),
    (COMMENT_STATUS_CHECK_LEAD_COMMENT, '审核表主管领导意见'),
    (COMMENT_STATUS_CHECK_QUALITY_COMMENT, '审核表质量部意见'),
    (COMMENT_STATUS_CHECK_ECONOMIC_COMMENT, '审核表经济运行部意见'),
    (COMMENT_STATUS_CHECK_COMPREHENSIVE_COMMENT, '审核表综合管理部意见'),
    (COMMENT_STATUS_QUALITY_FILL, '比质卡填写'),
    (COMMENT_STATUS_QUALITY_OPERATOR_COMMENT, '比质卡经办人意见'),
    (COMMENT_STATUS_QUALITY_NEED_TECH_COMMENT, '比质卡需求技术意见'),
    (COMMENT_STATUS_QUALITY_NEED_LEAD_COMMENT, '比质卡需求领导意见'),
    (COMMENT_STATUS_QUALITY_COMPREHENSIVE_COMMENT, '比质卡综合管理意见'),
    (COMMENT_STATUS_QUALITY_COMPANY_COMMENT, '比质卡公司意见'),
    (COMMENT_STATUS_MATERIEL_SUBSTITUDE_FILL, '代用单填写'),
    (COMMENT_STATUS_MATERIEL_SUBSTITUDE_MATERIEL, '材料工程师'),
    (COMMENT_STATUS_MATERIEL_SUBSTITUDE_PROCESS, '工艺工程师'),
    (COMMENT_STATUS_MATERIEL_SUBSTITUDE_WELDING, '焊接工程师'),
    (COMMENT_STATUS_MATERIEL_SUBSTITUDE_DESIGN, '设计工程师'),
    (COMMENT_STATUS_MATERIEL_SUBSTITUDE_ORIGINAL, '原设计单位'),
    (COMMENT_STATUS_MATERIEL_SUBSTITUDE_FINISH, '材料代用结束'),
    (COMMENT_STATUS_APPLY_FINISH, '结束'),
)

MATERIEL_TYPE_MAIN_MATERIEL = 0
MATERIEL_TYPE_SUPPORT_MATERIEL = 1
MATERIEL_TYPE_CHOICES = (
    (MATERIEL_TYPE_MAIN_MATERIEL, '主材'),
    (MATERIEL_TYPE_SUPPORT_MATERIEL, '辅材'),
)

# 标单评论人属性
COMMENT_USER_Z_APPLY_OPERATOR = 0
COMMENT_USER_Z_APPLY_LEAD = 1
COMMENT_USER_Z_NEED = 2
COMMENT_USER_Z_CENTRALIZE = 3
COMMENT_USER_Z_LOGISTICAL = 4
COMMENT_USER_Z_COMPANY = 5
COMMENT_USER_G_OPERATOR = 6
COMMENT_USER_G_LEAD = 7
COMMENT_USER_G_QUALITY = 8
COMMENT_USER_G_ECONOMIC = 9
COMMENT_USER_G_COMPREHENSIVE = 10
COMMENT_USER_Q_OPERATOR = 11
COMMENT_USER_Q_NEED_TECH = 12
COMMENT_USER_Q_NEED_LEAD = 13
COMMENT_USER_Q_COMPREHENSIVE = 14
COMMENT_USER_Q_COMPANY = 15
COMMENT_USER_S_MATERIEL = 16
COMMENT_USER_S_PROCESS = 17
COMMENT_USER_S_WELDING = 18
COMMENT_USER_S_DESIGN = 19
COMMENT_USER_S_ORIGINAL = 20

COMMENT_USER_CHOICES = (
    (COMMENT_USER_Z_APPLY_OPERATOR, '申请表经办人'),
    (COMMENT_USER_Z_APPLY_LEAD, '申请表申请主管'),
    (COMMENT_USER_Z_NEED, '申请表需求单位'),
    (COMMENT_USER_Z_CENTRALIZE, '申请表归口部门'),
    (COMMENT_USER_Z_LOGISTICAL, '申请表物流采控'),
    (COMMENT_USER_Z_COMPANY, '申请表公司意见'),
    (COMMENT_USER_G_OPERATOR, '审核表经办人'),
    (COMMENT_USER_G_LEAD, '审核表主管领导'),
    (COMMENT_USER_G_QUALITY, '审核表质量部'),
    (COMMENT_USER_G_ECONOMIC, '审核表经济运行部'),
    (COMMENT_USER_G_COMPREHENSIVE, '审核表综合管理部'),
    (COMMENT_USER_Q_OPERATOR, '比质卡经办人'),
    (COMMENT_USER_Q_NEED_TECH, '比质卡需求技术'),
    (COMMENT_USER_Q_NEED_LEAD, '比质卡需求领导'),
    (COMMENT_USER_Q_COMPREHENSIVE, '比质卡综合管理'),
    (COMMENT_USER_Q_COMPANY, '比质卡公司意见'),
    (COMMENT_USER_S_MATERIEL, '代用材料责任工程师'),
    (COMMENT_USER_S_PROCESS, '代用工艺责任工程师'),
    (COMMENT_USER_S_WELDING, '代用焊接责任工程师'),
    (COMMENT_USER_S_DESIGN, '代用设计责任工程师'),
    (COMMENT_USER_S_ORIGINAL, '代用原设计单位'),
)


SUPPLIER_SELECT_C_ENTITY = 0
SUPPLIER_SELECT_C_TRADE = 1
SUPPLIER_SELECT_C_CHOICES = (
    (SUPPLIER_SELECT_C_ENTITY, '实体'),
    (SUPPLIER_SELECT_C_TRADE, '贸易'),
)
