# TODO: Review names
SIG_AUXILIARY = 0
SIG_PRINCIPAL = 1
SIG_COOPERANT = 2
SIG_FIRSTFEEDING = 3
SIG_OUTPURCHASED = 4
SIG_WELDLISTPAGE = 5
SIG_TRANSFERCARD = 6
SIG_PROCESSBOMPAGE = 7
SIG_BOXOUTBOUGHT = 8
SIG_DESIGNBOM = 9
SIG_WELDQUOTAPAGE = 10

SIGNATURE_CATEGORY_CHOICES = (
    (SIG_AUXILIARY, '辅材定额明细签章'),
    (SIG_PRINCIPAL, '主材定额明细签章'),
    (SIG_COOPERANT, '工序性外协明细签章'),
    (SIG_FIRSTFEEDING, '先投件明细签章'),
    (SIG_OUTPURCHASED, '外购件明细签章'),
    (SIG_WELDLISTPAGE, '焊缝明细签章'),
    (SIG_TRANSFERCARD, '流转卡签章'),
    (SIG_PROCESSBOMPAGE, '工艺库签章'),
    (SIG_BOXOUTBOUGHT, '装箱外购件明细签章'),
    (SIG_DESIGNBOM, '设计库签章'),
    (SIG_WELDQUOTAPAGE, '焊材明细签章'),
)

PROCESS_W = 0
PROCESS_W1 = 1
PROCESS_W2 = 2
PROCESS_W3 = 3
PROCESS_W4 = 4
PROCESS_W5 = 5
PROCESS_W6 = 6
PROCESS_W25 = 7
PROCESS_P01 = 8
PROCESS_P02 = 9
PROCESS_R = 10
PROCESS_R1 = 11
PROCESS_R2 = 12
PROCESS_Z = 13
PROCESS_H = 14
PROCESS_M = 15
PROCESS_L = 16
PROCESS_Y = 17
PROCESS_G = 18
PROCESS_G1 = 19
PROCESS_G2 = 20
PROCESS_G3 = 21
PROCESS_G4 = 22
PROCESS_G5 = 23
PROCESS_X = 24
PROCESS_J = 25
PROCESS_K = 26
PROCESS_D2 = 27
PROCESS_D = 28

PROCESS_CHOICES = (
    (PROCESS_W, 'W'),
    (PROCESS_W1, 'W1'),
    (PROCESS_W2, 'W2'),
    (PROCESS_W3, 'W3'),
    (PROCESS_W4, 'W4'),
    (PROCESS_W5, 'W5'),
    (PROCESS_W6, 'W6'),
    (PROCESS_W25, 'W25'),
    (PROCESS_P01, 'P01'),
    (PROCESS_P02, 'P02'),
    (PROCESS_R, 'R'),
    (PROCESS_R1, 'R1'),
    (PROCESS_R2, 'R2'),
    (PROCESS_Z, 'Z'),
    (PROCESS_H, 'H'),
    (PROCESS_M, 'M'),
    (PROCESS_L, 'L'),
    (PROCESS_Y, 'Y'),
    (PROCESS_G, 'G'),
    (PROCESS_G1, 'G1'),
    (PROCESS_G2, 'G2'),
    (PROCESS_G3, 'G3'),
    (PROCESS_G4, 'G4'),
    (PROCESS_G5, 'G5'),
    (PROCESS_X, 'X'),
    (PROCESS_J, 'J'),
    (PROCESS_D, 'D'),
    (PROCESS_D2, 'D2'),
    (PROCESS_K, 'K'),
)

CIRCULATION_H1 = 0
CIRCULATION_J = 1
CIRCULATION_R = 3
CIRCULATION_ZM = 4
CIRCULATION_GY = 5
CIRCULATION_DY = 6
CIRCULATION_XZ = 7

CIRCULATION_CHOICES = (
    (CIRCULATION_H1, 'H1'),
    (CIRCULATION_J, 'J'),
    (CIRCULATION_ZM, 'ZM'),
    (CIRCULATION_R, 'R'),
    (CIRCULATION_GY, 'GY'),
    (CIRCULATION_DY, 'DY'),
    (CIRCULATION_XZ, 'XZ'),
)

WELD_METHOD_SMAW = 0
WELD_METHOD_SAW = 1
WELD_METHOD_GMAW = 2
WELD_METHOD_GTAW = 3
WELD_METHODS = (
    (WELD_METHOD_SMAW, '焊条电弧焊'),
    (WELD_METHOD_SAW, '埋弧焊'),
    (WELD_METHOD_GMAW, '气体保护焊'),
    (WELD_METHOD_GTAW, '氩弧焊'),
)

NONDESTRUCTIVE_INSPECTION_RT = 0
NONDESTRUCTIVE_INSPECTION_UT = 1
NONDESTRUCTIVE_INSPECTION_MT = 2
NONDESTRUCTIVE_INSPECTION_PT = 3
NONDESTRUCTIVE_INSPECTION_VT = 4

NONDESTRUCTIVE_INSPECTION_TYPES = (
    (NONDESTRUCTIVE_INSPECTION_RT, 'RT'),
    (NONDESTRUCTIVE_INSPECTION_UT, 'UT'),
    (NONDESTRUCTIVE_INSPECTION_MT, 'MT'),
    (NONDESTRUCTIVE_INSPECTION_PT, 'PT'),
    (NONDESTRUCTIVE_INSPECTION_VT, 'VT'),
)


#焊接工艺评定编号
RH24_13_09 = 0
RH24_13_36 = 1
PROCEDURE_QUALIFICATION_INDEXS = (
    (RH24_13_09, 'RH24-13-09'),
    (RH24_13_36, 'RH24-13-36'),
)

WELD_POS_FLUSH_WELD = 0
WELD_POS_HORIZONTAL_WELD = 1
WELD_POS_OVERHEAD_WELD = 2
WELD_POS_VERTICAL_WELD = 3
WELD_POS_WIDE_WELD = 4

WELD_POSITION_CHOICES = (
    (WELD_POS_FLUSH_WELD, '平焊'),
    (WELD_POS_HORIZONTAL_WELD, '横焊'),
    (WELD_POS_OVERHEAD_WELD, '仰焊'),
    (WELD_POS_VERTICAL_WELD, '立向上焊'),
    (WELD_POS_WIDE_WELD, '全位置焊')
)

