# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:21
from __future__ import unicode_literals

import Core.utils.generates
import Core.utils.hash
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Process', '0001_initial'),
        ('Core', '0002_auto_20171206_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_confirm', models.BooleanField(default=False, verbose_name='实物确认')),
                ('soft_confirm', models.BooleanField(default=False, verbose_name='软件确认')),
                ('inspection_confirm', models.BooleanField(default=False, verbose_name='检验通过')),
                ('passed', models.BooleanField(default=False, verbose_name='是否通过')),
            ],
            options={
                'verbose_name': '到货检验',
                'verbose_name_plural': '到货检验',
            },
        ),
        migrations.CreateModel(
            name='BiddingAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='标书编号')),
                ('requestor', models.CharField(blank=True, default='', max_length=40, verbose_name='招（议）标单位')),
                ('content', models.CharField(blank=True, default='', max_length=40, verbose_name='招（议）标内容')),
                ('amount', models.CharField(max_length=40, null=True, verbose_name='数量')),
                ('accept_date', models.DateField(blank=True, null=True, verbose_name='中标日期')),
                ('accept_money', models.CharField(blank=True, max_length=40, null=True, verbose_name='中标金额')),
                ('contact', models.CharField(blank=True, max_length=40, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '中标通知书',
                'verbose_name_plural': '中标通知书',
            },
        ),
        migrations.CreateModel(
            name='BiddingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='标单申请编号')),
                ('applicant', models.CharField(max_length=40, verbose_name='申请单位')),
                ('requestor', models.CharField(max_length=40, verbose_name='需求单位')),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('work_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='工作令')),
                ('plan_project', models.CharField(blank=True, max_length=40, null=True, verbose_name='拟招(议)项目')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='拟招(议)标时间')),
                ('model', models.CharField(blank=True, max_length=40, null=True, verbose_name='规格、型号')),
                ('is_core_part', models.BooleanField(default=False, verbose_name='是否为核心件')),
                ('category', models.CharField(blank=True, max_length=40, null=True, verbose_name='项目类别')),
                ('tender_date', models.DateField(blank=True, null=True, verbose_name='招(议)标时间')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='标书递送时间')),
                ('place', models.CharField(blank=True, max_length=40, null=True, verbose_name='地点')),
                ('status', models.IntegerField(choices=[(0, '申请表填写'), (1, '申请经办人意见'), (2, '申请表申请领导意见'), (3, '申请表需求部门意见'), (4, '申请表归口部门意见'), (5, '申请表物流采控部门意见'), (6, '申请表公司意见'), (7, '审核表填写'), (8, '审核表经办人意见'), (9, '审核表主管领导意见'), (10, '审核表质量部意见'), (11, '审核表经济运行部意见'), (12, '审核表综合管理部意见'), (13, '比质卡填写'), (14, '比质卡经办人意见'), (15, '比质卡需求技术意见'), (16, '比质卡需求领导意见'), (17, '比质卡综合管理意见'), (18, '比质卡公司意见'), (20, '代用单填写'), (21, '材料工程师'), (22, '工艺工程师'), (23, '焊接工程师'), (24, '设计工程师'), (25, '原设计单位'), (26, '材料代用结束'), (19, '结束')], verbose_name='状态')),
                ('implement_class', models.IntegerField(choices=[(0, '招标'), (1, '议标')], verbose_name='实施类别')),
            ],
            options={
                'verbose_name': '标单申请表',
                'verbose_name_plural': '标单申请表',
            },
        ),
        migrations.CreateModel(
            name='BiddingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='意见内容')),
                ('submit_dt', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('user_title', models.IntegerField(choices=[(0, '申请表经办人'), (1, '申请表申请主管'), (2, '申请表需求单位'), (3, '申请表归口部门'), (4, '申请表物流采控'), (5, '申请表公司意见'), (6, '审核表经办人'), (7, '审核表主管领导'), (8, '审核表质量部'), (9, '审核表经济运行部'), (10, '审核表综合管理部'), (11, '比质卡经办人'), (12, '比质卡需求技术'), (13, '比质卡需求领导'), (14, '比质卡综合管理'), (15, '比质卡公司意见'), (16, '代用材料责任工程师'), (17, '代用工艺责任工程师'), (18, '代用焊接责任工程师'), (19, '代用设计责任工程师'), (20, '代用原设计单位')], verbose_name='审批人头衔')),
            ],
            options={
                'verbose_name': '标单评审意见',
                'verbose_name_plural': '标单评审意见',
            },
        ),
        migrations.CreateModel(
            name='BiddingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='标单编号')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='创建日期')),
                ('status', models.IntegerField(choices=[(0, '标单创建'), (1, '供应商选择'), (2, '招标申请选择'), (3, '招标申请填写'), (4, '招标中'), (5, '中标确认'), (6, '进程跟踪'), (7, '标单检验'), (8, '标单入库'), (9, '标单完成'), (10, '标单终止')], unique=True, verbose_name='标单状态')),
                ('contract_number', models.CharField(blank=True, default=Core.utils.generates.gen_uuid, max_length=50, verbose_name='合同编号')),
                ('contract_amount', models.IntegerField(default=0, verbose_name='合同金额')),
                ('billing_amount', models.IntegerField(default=0, verbose_name='开票金额')),
                ('category', models.IntegerField(default=0, verbose_name='招标申请类型')),
            ],
            options={
                'verbose_name': '标单',
                'verbose_name_plural': '标单',
            },
        ),
        migrations.CreateModel(
            name='ContractDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_dt', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('bidding_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': '合同金额明细',
                'verbose_name_plural': '合同金额明细',
            },
        ),
        migrations.CreateModel(
            name='MaterialExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('list_date', models.DateField(verbose_name='制表日期')),
                ('material_type', models.IntegerField(choices=[(0, '主材'), (1, '辅材')], verbose_name='材料类型')),
                ('saved', models.BooleanField(default=False, verbose_name='已保存')),
                ('process_requirement', models.CharField(blank=True, default='', max_length=200, verbose_name='工艺需求')),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='制表人')),
            ],
            options={
                'verbose_name': '材料执行表',
                'verbose_name_plural': '材料执行表',
            },
        ),
        migrations.CreateModel(
            name='MaterialExecutionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='出厂批号')),
                ('quota', models.CharField(blank=True, max_length=50, null=True, verbose_name='定额')),
                ('part', models.CharField(blank=True, max_length=50, null=True, verbose_name='零件')),
                ('oddments', models.CharField(blank=True, max_length=50, null=True, verbose_name='余料')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '材料执行表明细',
                'verbose_name_plural': '材料执行表明细',
            },
        ),
        migrations.CreateModel(
            name='MaterialSubApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30, unique=True, verbose_name='单据编号')),
                ('figure_code', models.CharField(blank=True, default='', max_length=30, verbose_name='图号')),
                ('work_order', models.CharField(blank=True, default='', max_length=30, verbose_name='工作令')),
                ('production', models.CharField(blank=True, default='', max_length=50, verbose_name='产品名称')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='代用原因和理由')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '材料代用申请单',
                'verbose_name_plural': '材料代用申请单',
            },
        ),
        migrations.CreateModel(
            name='MaterialSubApplyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_figure_code', models.CharField(max_length=100, verbose_name='部件图号')),
                ('part_ticket_code', models.CharField(max_length=100, verbose_name='零件图号或票号')),
                ('old_name', models.CharField(max_length=100, verbose_name='原材料名称')),
                ('old_standard', models.CharField(max_length=100, verbose_name='原材料标准')),
                ('old_size', models.CharField(max_length=100, verbose_name='原材料规格和尺寸')),
                ('new_name', models.CharField(max_length=100, verbose_name='拟用材料名称')),
                ('new_standard', models.CharField(max_length=100, verbose_name='拟用材料标准')),
                ('new_size', models.CharField(max_length=100, verbose_name='拟用材料规格和尺寸')),
                ('sub_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.MaterialSubApply', verbose_name='材料代用申请单')),
            ],
            options={
                'verbose_name': '材料代用申请单明细',
                'verbose_name_plural': '材料代用申请单明细',
            },
        ),
        migrations.CreateModel(
            name='ParityRatioCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_id', models.CharField(max_length=20, verbose_name='标单申请编号')),
                ('applicant', models.CharField(max_length=40, verbose_name='申请单位')),
                ('requestor', models.CharField(max_length=40, verbose_name='需求单位')),
                ('work_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作令')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=40, null=True, verbose_name='单位')),
                ('content', models.CharField(blank=True, max_length=40, null=True, verbose_name='内容')),
                ('material', models.CharField(blank=True, max_length=40, null=True, verbose_name='材质')),
                ('delivery_period', models.CharField(blank=True, max_length=40, null=True, verbose_name='交货期')),
                ('status', models.IntegerField(choices=[(0, '申请表填写'), (1, '申请经办人意见'), (2, '申请表申请领导意见'), (3, '申请表需求部门意见'), (4, '申请表归口部门意见'), (5, '申请表物流采控部门意见'), (6, '申请表公司意见'), (7, '审核表填写'), (8, '审核表经办人意见'), (9, '审核表主管领导意见'), (10, '审核表质量部意见'), (11, '审核表经济运行部意见'), (12, '审核表综合管理部意见'), (13, '比质卡填写'), (14, '比质卡经办人意见'), (15, '比质卡需求技术意见'), (16, '比质卡需求领导意见'), (17, '比质卡综合管理意见'), (18, '比质卡公司意见'), (20, '代用单填写'), (21, '材料工程师'), (22, '工艺工程师'), (23, '焊接工程师'), (24, '设计工程师'), (25, '原设计单位'), (26, '材料代用结束'), (19, '结束')], verbose_name='状态')),
                ('bidding_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单')),
            ],
            options={
                'verbose_name': '比质比价卡',
                'verbose_name_plural': '比质比价卡',
            },
        ),
        migrations.CreateModel(
            name='ProcessFollowingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_date', models.DateField(verbose_name='跟踪日期')),
                ('following_method', models.CharField(max_length=20, verbose_name='跟踪方式')),
                ('following_feedback', models.CharField(max_length=200, verbose_name='跟踪反馈')),
                ('path', models.FileField(upload_to=Core.utils.hash.DynamicHashPath('ProcessFollowingInfo'), verbose_name='路径')),
                ('inform_process', models.BooleanField(default=False, verbose_name='是否通知工艺')),
                ('bidding_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '过程跟踪记录',
                'verbose_name_plural': '过程跟踪记录',
            },
        ),
        migrations.CreateModel(
            name='ProcurementMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.IntegerField(choices=[(-1, '未设置'), (0, '主材定额'), (1, '辅材定额'), (2, '先投件明细'), (3, '外购件明细'), (4, '焊材定额'), (5, '工序性外协明细')], default=-1, verbose_name='明细类型')),
                ('batch_number', models.CharField(blank=True, default='', max_length=50, verbose_name='炉批号')),
                ('material_number', models.CharField(blank=True, default='', max_length=50, verbose_name='材质编号')),
                ('delivery_dt', models.DateTimeField(blank=True, null=True, verbose_name='交货期')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='材料分类')),
                ('finished', models.BooleanField(default=False, verbose_name='是否结束')),
                ('add_to_detail', models.BooleanField(default=False, verbose_name='已加入物料汇总')),
                ('merged_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.ProcurementMaterial', verbose_name='合并后物料')),
                ('process_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Process.ProcessMaterial', verbose_name='工艺物料')),
            ],
            options={
                'verbose_name': '采购物料',
                'verbose_name_plural': '采购物料',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.IntegerField(choices=[(0, '创建中订购单'), (1, '创建完成订购单'), (2, '审核通过订购单'), (3, '批准通过订购单'), (4, '已终止历史订购单')], verbose_name='订购单状态')),
                ('list_date', models.DateTimeField(blank=True, null=True, verbose_name='编制日期')),
                ('audit_date', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='批准日期')),
                ('tech_requirement', models.TextField(blank=True, default='', max_length=1000, verbose_name='工艺需求')),
                ('category', models.IntegerField(verbose_name='标单类型')),
                ('revised_number', models.CharField(blank=True, default='', max_length=50, verbose_name='修订号')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_approver', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_chief', to=settings.AUTH_USER_MODEL, verbose_name='外采科长')),
                ('lister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lister', to=settings.AUTH_USER_MODEL, verbose_name='编制人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.WorkOrder', verbose_name='工作令')),
            ],
            options={
                'verbose_name': '订购单',
                'verbose_name_plural': '订购单',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.IntegerField(choices=[(-1, '未设置'), (0, '主材定额'), (1, '辅材定额'), (2, '先投件明细'), (3, '外购件明细'), (4, '焊材定额'), (5, '工序性外协明细')], default=-1, verbose_name='明细类型')),
                ('name_spec', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格及名称')),
                ('material_mark', models.CharField(blank=True, max_length=50, null=True, verbose_name='材质或牌号')),
                ('unit_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='单价')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='单位')),
            ],
            options={
                'verbose_name': '报价单',
                'verbose_name_plural': '报价单',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.IntegerField(choices=[(0, '标单创建'), (1, '供应商选择'), (2, '招标申请选择'), (3, '招标申请填写'), (4, '招标中'), (5, '中标确认'), (6, '进程跟踪'), (7, '标单检验'), (8, '标单入库'), (9, '标单完成'), (10, '标单终止')], unique=True, verbose_name='标单状态')),
                ('new_status', models.IntegerField(choices=[(0, '标单创建'), (1, '供应商选择'), (2, '招标申请选择'), (3, '招标申请填写'), (4, '招标中'), (5, '中标确认'), (6, '进程跟踪'), (7, '标单检验'), (8, '标单入库'), (9, '标单完成'), (10, '标单终止')], unique=True, verbose_name='标单状态')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='更改时间')),
                ('normal_change', models.BooleanField(default=True, verbose_name='是否正常更改')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='回溯原因')),
                ('bidding_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单')),
                ('change_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='更改用户')),
            ],
            options={
                'verbose_name': '状态更改记录',
                'verbose_name_plural': '状态更改记录',
            },
        ),
        migrations.CreateModel(
            name='SubApplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='意见内容')),
                ('submit_dt', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('user_title', models.IntegerField(choices=[(0, '申请表经办人'), (1, '申请表申请主管'), (2, '申请表需求单位'), (3, '申请表归口部门'), (4, '申请表物流采控'), (5, '申请表公司意见'), (6, '审核表经办人'), (7, '审核表主管领导'), (8, '审核表质量部'), (9, '审核表经济运行部'), (10, '审核表综合管理部'), (11, '比质卡经办人'), (12, '比质卡需求技术'), (13, '比质卡需求领导'), (14, '比质卡综合管理'), (15, '比质卡公司意见'), (16, '代用材料责任工程师'), (17, '代用工艺责任工程师'), (18, '代用焊接责任工程师'), (19, '代用设计责任工程师'), (20, '代用原设计单位')], verbose_name='审批人属性')),
                ('sub_apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.MaterialSubApply', verbose_name='材料代用申请单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '材料代用评审意见',
                'verbose_name_plural': '材料代用评审意见',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='供应商编号')),
                ('name', models.CharField(max_length=50, verbose_name='供应商名称')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='SupplierCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=40, verbose_name='申请单位')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('project', models.CharField(max_length=40, verbose_name='项目名称')),
                ('estimated_price', models.FloatField(verbose_name='估算价格')),
                ('basic_situation', models.CharField(blank=True, default='', max_length=100, verbose_name='招（议）标项目基本情况')),
                ('status', models.IntegerField(choices=[(0, '申请表填写'), (1, '申请经办人意见'), (2, '申请表申请领导意见'), (3, '申请表需求部门意见'), (4, '申请表归口部门意见'), (5, '申请表物流采控部门意见'), (6, '申请表公司意见'), (7, '审核表填写'), (8, '审核表经办人意见'), (9, '审核表主管领导意见'), (10, '审核表质量部意见'), (11, '审核表经济运行部意见'), (12, '审核表综合管理部意见'), (13, '比质卡填写'), (14, '比质卡经办人意见'), (15, '比质卡需求技术意见'), (16, '比质卡需求领导意见'), (17, '比质卡综合管理意见'), (18, '比质卡公司意见'), (20, '代用单填写'), (21, '材料工程师'), (22, '工艺工程师'), (23, '焊接工程师'), (24, '设计工程师'), (25, '原设计单位'), (26, '材料代用结束'), (19, '结束')], verbose_name='状态')),
                ('bidding_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单')),
            ],
            options={
                'verbose_name': '供应商审核',
                'verbose_name_plural': '供应商审核',
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to=Core.utils.hash.DynamicHashPath('SupplierDocument'), verbose_name='路径')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '供应商文件',
                'verbose_name_plural': '供应商文件',
            },
        ),
        migrations.CreateModel(
            name='SupplyRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.BooleanField(default=False, verbose_name='A')),
                ('B', models.BooleanField(default=False, verbose_name='B')),
                ('C', models.IntegerField(choices=[(0, '实体'), (1, '贸易')], verbose_name='C')),
                ('D', models.BooleanField(default=False, verbose_name='D')),
                ('E', models.BooleanField(default=False, verbose_name='E')),
                ('F', models.BooleanField(default=False, verbose_name='F')),
                ('G', models.BooleanField(default=False, verbose_name='G')),
                ('scope', models.CharField(blank=True, default='', max_length=40, verbose_name='认定业务范围')),
                ('supplier_code', models.CharField(blank=True, default='', max_length=40, verbose_name='供方代码')),
                ('price', models.FloatField(verbose_name='价格')),
                ('status', models.CharField(blank=True, default='', max_length=100, verbose_name='厂家协作能力质量情况及业绩')),
                ('delivery_payment', models.CharField(blank=True, default='', max_length=40, verbose_name='交货及支付条件')),
                ('bidding_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '标单供应关系',
                'verbose_name_plural': '标单供应关系',
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='bidding_sheets',
            field=models.ManyToManyField(through='Procurement.SupplyRelationship', to='Procurement.BiddingSheet', verbose_name='参与标单'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.Supplier', verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='procurementmaterial',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.PurchaseOrder', verbose_name='订购单'),
        ),
        migrations.AddField(
            model_name='procurementmaterial',
            name='sub_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.SubWorkOrder', verbose_name='子工作令'),
        ),
        migrations.AddField(
            model_name='materialexecutiondetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.ProcurementMaterial', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='materialexecutiondetail',
            name='material_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.MaterialExecution', verbose_name='材料执行表'),
        ),
        migrations.AddField(
            model_name='biddingsheet',
            name='purchase_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.PurchaseOrder', verbose_name='对应订购单'),
        ),
        migrations.AddField(
            model_name='biddingcomment',
            name='bidding_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AddField(
            model_name='biddingcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='biddingapplication',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AddField(
            model_name='biddingacceptance',
            name='accept_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Procurement.Supplier', verbose_name='中标单位'),
        ),
        migrations.AddField(
            model_name='biddingacceptance',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AddField(
            model_name='arrivalinspection',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Procurement.ProcurementMaterial', verbose_name='材料'),
        ),
    ]
