# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsubapplyitems',
            name='sub_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Procurement.MaterialSubApply', verbose_name='材料代用申请单'),
        ),
    ]
