# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0002_auto_20171215_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuschange',
            old_name='change_time',
            new_name='change_dt',
        ),
        migrations.RemoveField(
            model_name='biddingacceptance',
            name='accept_date',
        ),
        migrations.RemoveField(
            model_name='biddingapplication',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='biddingapplication',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='biddingapplication',
            name='tender_date',
        ),
        migrations.RemoveField(
            model_name='biddingsheet',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='materialexecution',
            name='list_date',
        ),
        migrations.RemoveField(
            model_name='processfollowinginfo',
            name='following_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='approve_time',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='audit_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='list_date',
        ),
        migrations.RemoveField(
            model_name='suppliercheck',
            name='application_date',
        ),
        migrations.AddField(
            model_name='biddingacceptance',
            name='accept_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='中标时间'),
        ),
        migrations.AddField(
            model_name='biddingapplication',
            name='delivery_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='标书递送时间'),
        ),
        migrations.AddField(
            model_name='biddingapplication',
            name='plan_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拟招(议)标时间'),
        ),
        migrations.AddField(
            model_name='biddingapplication',
            name='tender_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='招(议)标时间'),
        ),
        migrations.AddField(
            model_name='biddingsheet',
            name='create_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='materialexecution',
            name='list_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='制表时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processfollowinginfo',
            name='following_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='跟踪时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approve_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批准时间'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='audit_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='list_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='编制时间'),
        ),
        migrations.AddField(
            model_name='suppliercheck',
            name='application_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biddingcomment',
            name='submit_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='submit_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='subapplycomment',
            name='submit_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
    ]
