# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0003_auto_20171222_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialexecution',
            name='saved',
        ),
        migrations.AlterField(
            model_name='materialexecution',
            name='list_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='制表时间'),
        ),
        migrations.AlterField(
            model_name='materialexecutiondetail',
            name='material_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialexecution', to='Procurement.MaterialExecution', verbose_name='材料执行表'),
        ),
        migrations.AlterField(
            model_name='materialsubapplyitems',
            name='sub_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_apply_items', to='Procurement.MaterialSubApply', verbose_name='材料代用申请单'),
        ),
        migrations.AlterField(
            model_name='subapplycomment',
            name='sub_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_spply_comments', to='Procurement.MaterialSubApply', verbose_name='材料代用申请单'),
        ),
    ]
