# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0005_auto_20171225_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementmaterial',
            name='count',
            field=models.IntegerField(default=0, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementmaterial',
            name='weight',
            field=models.FloatField(default=0, verbose_name='重量'),
            preserve_default=False,
        ),
    ]
