# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0006_auto_20171229_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialexecutiondetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='Procurement.ProcurementMaterial', verbose_name='物料'),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='new_status',
            field=models.IntegerField(choices=[(0, '标单创建'), (1, '供应商选择'), (2, '招标申请选择'), (3, '招标申请填写'), (4, '招标中'), (5, '中标确认'), (6, '进程跟踪'), (7, '标单检验'), (8, '标单入库'), (9, '标单完成'), (10, '标单终止')], verbose_name='标单状态'),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='original_status',
            field=models.IntegerField(choices=[(0, '标单创建'), (1, '供应商选择'), (2, '招标申请选择'), (3, '招标申请填写'), (4, '招标中'), (5, '中标确认'), (6, '进程跟踪'), (7, '标单检验'), (8, '标单入库'), (9, '标单完成'), (10, '标单终止')], verbose_name='标单状态'),
        ),
    ]
