# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0007_auto_20171230_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementmaterial',
            name='add_to_detail',
        ),
        migrations.AddField(
            model_name='procurementmaterial',
            name='status',
            field=models.IntegerField(choices=[(0, '材料待处理'), (1, '已加入物料汇总'), (2, '已加入订购单'), (3, '已加入材料执行'), (4, '材料执行完成')], default=0, verbose_name='物料状态'),
        ),
    ]
