# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0008_auto_20180118_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialexecutiondetail',
            name='batch_number',
        ),
        migrations.AlterField(
            model_name='materialexecutiondetail',
            name='material_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_details', to='Procurement.MaterialExecution', verbose_name='材料执行表'),
        ),
    ]
