# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0009_auto_20180119_1656'),
        ('Procurement', '0009_auto_20180122_1041'),
    ]

    operations = [
    ]
