# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0010_merge_20180122_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='work_order',
        ),
    ]
