# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0011_remove_purchaseorder_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.IntegerField(choices=[(0, '创建中订购单'), (1, '创建完成订购单'), (2, '审核通过订购单'), (3, '批准通过订购单'), (4, '已终止历史订购单')], default=0, verbose_name='订购单状态'),
        ),
    ]
