# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0012_auto_20180122_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingsheet',
            name='status',
            field=models.IntegerField(choices=[(0, '标单创建'), (1, '供应商选择'), (2, '招标申请选择'), (3, '招标申请填写'), (4, '招标中'), (5, '中标确认'), (6, '进程跟踪'), (7, '标单检验'), (8, '标单入库'), (9, '标单完成'), (10, '标单终止')], verbose_name='标单状态'),
        ),
        migrations.AlterField(
            model_name='supplyrelationship',
            name='C',
            field=models.IntegerField(blank=True, choices=[(0, '实体'), (1, '贸易')], null=True, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='supplyrelationship',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
