# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0012_auto_20180122_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingacceptance',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_acceptance', to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AlterField(
            model_name='biddingapplication',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_application', to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
        migrations.AlterField(
            model_name='parityratiocard',
            name='bidding_sheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parity_ratio_card', to='Procurement.BiddingSheet', verbose_name='标单'),
        ),
    ]
