# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procurement', '0013_auto_20180125_0023'),
        ('Procurement', '0013_auto_20180124_1648'),
    ]

    operations = [
    ]
